-- Add Ed25519 signature column to game_receipts.
--
-- Cook receipts generated by `rocket html5 verify` are signed with the
-- server's Ed25519 private key (ROCKET_SIGNING_KEY env var). The signature
-- is stored here for browser and CLI verification via ROCKET_SIGNING_PUBKEY.
--
-- Non-null only for receipts that came through the Rust CLI pipeline — browser
-- receipts (from /api/game/receipt) are not signed because the browser doesn't
-- have access to the private key.
--
-- Signed payload (sorted-key canonical JSON, matches signing.rs):
--   {"proven_at":<iso>, "receipt_hash":<sha256:hex>, "session_id":<uuid|null>, "verdict":<PASS|FAIL>}

ALTER TABLE game_receipts
  ADD COLUMN IF NOT EXISTS ed25519_sig TEXT;

ALTER TABLE game_receipts
  ADD COLUMN IF NOT EXISTS signed_by TEXT;

COMMENT ON COLUMN game_receipts.ed25519_sig IS
  'Base64-encoded Ed25519 signature over canonical JSON {proven_at,receipt_hash,session_id,verdict}. '
  'Verify with ROCKET_SIGNING_PUBKEY from environment. NULL for browser receipts.';

COMMENT ON COLUMN game_receipts.signed_by IS
  'Identifier of the signing key (e.g. "rocket-cli-v1"). '
  'Enables key rotation without breaking historical verification.';
