import os

py_path = "/Users/sac/rocket-craft/patch_geometry_generator.py"

if not os.path.exists(py_path):
    print(f"Error: {py_path} not found")
    exit(1)

with open(py_path, "r") as f:
    content = f.read()

start_token = 'part_mesh_tera = """#usda 1.0'
end_token = '"""\n\nwith open(f"{base_dir}/templates/usd/part_mesh.usda.tera"'

if start_token not in content or end_token not in content:
    print("Error: Start or end token not found in patch_geometry_generator.py")
    exit(1)

parts_before = content.split(start_token)
parts_after = parts_before[1].split(end_token)

new_part_mesh_tera = """part_mesh_tera = \"\"\"#usda 1.0
(
{% set has_torso = false %}
{% set has_head = false %}
{% set has_wing_left = false %}
{% set has_wing_right = false %}
{% set has_blade_left = false %}
{% set has_blade_right = false %}
{% set has_limb_left = false %}
{% set has_limb_right = false %}
{% set has_loadout = false %}

{% for row in results %}
    {% if row.partLocalName == "torso_core" %}
        {% set_global has_torso = true %}
    {% elif row.partLocalName == "head_unit" or row.partLocalName == "v_fin_left" or row.partLocalName == "v_fin_right" %}
        {% set_global has_head = true %}
    {% elif row.partLocalName == "wing_root_left" or row.partLocalName == "primary_wing_feathers_left" or row.partLocalName == "secondary_wing_feathers_left" %}
        {% set_global has_wing_left = true %}
    {% elif row.partLocalName == "wing_root_right" or row.partLocalName == "primary_wing_feathers_right" or row.partLocalName == "secondary_wing_feathers_right" %}
        {% set_global has_wing_right = true %}
    {% elif row.partLocalName == "blade_left" %}
        {% set_global has_blade_left = true %}
    {% elif row.partLocalName == "blade_right" %}
        {% set_global has_blade_right = true %}
    {% elif row.partLocalName == "shoulder_left" or row.partLocalName == "arm_left" or row.partLocalName == "leg_left" %}
        {% set_global has_limb_left = true %}
    {% elif row.partLocalName == "shoulder_right" or row.partLocalName == "arm_right" or row.partLocalName == "leg_right" %}
        {% set_global has_limb_right = true %}
    {% elif row.partLocalName == "backpack_core" or row.partLocalName == "thruster_cluster" %}
        {% set_global has_loadout = true %}
    {% endif %}
{% endfor %}

{% if has_torso %}
    defaultPrim = "SM_Torso"
{% elif has_head %}
    defaultPrim = "SM_Head"
{% elif has_wing_left %}
    defaultPrim = "SM_WingArray_Left"
{% elif has_wing_right %}
    defaultPrim = "SM_WingArray_Right"
{% elif has_blade_left %}
    defaultPrim = "SM_Blade_Left"
{% elif has_blade_right %}
    defaultPrim = "SM_Blade_Right"
{% elif has_limb_left %}
    defaultPrim = "SM_Limb_Left"
{% elif has_limb_right %}
    defaultPrim = "SM_Limb_Right"
{% elif has_loadout %}
    defaultPrim = "SM_Loadout"
{% else %}
    defaultPrim = "SM_Unknown"
{% endif %}
    upAxis = "Y"
    metersPerUnit = 0.01
    doc = "Generated by ggen. Deterministic USD StaticMesh container."
)

{% macro render_primitive(row, is_right) %}
    {% if row.type == "socket" %}
        def Xform "{{ row.primLocalName }}"
        {
            double3 xformOp:translate = ({{ row.translateX }}, {{ row.translateY }}, {{ row.translateZ }})
            uniform token[] xformOpOrder = ["xformOp:translate"]
        }
    {% else %}
        def Xform "{{ row.primLocalName }}_group"
        {
            {% set my_ty = row.translateY %}
            {% set my_sy = row.scaleY %}
            {% set my_rz = row.rotateZ %}
            {% if row.partLocalName == "torso_core" %}
                {% set my_ty = 6.35 %}
                {% set my_sy = 0.65 %}
            {% elif row.partLocalName == "head_unit" %}
                {% set my_ty = 7.65 %}
                {% set my_sy = 0.65 %}
            {% elif row.partLocalName == "shoulder_left" or row.partLocalName == "shoulder_right" %}
                {% set my_ty = 2.60 %}
                {% set my_sy = 3.20 %}
            {% elif row.partLocalName == "primary_wing_feathers_left" or row.partLocalName == "primary_wing_feathers_right" %}
                {% set my_ty = 2.39 %}
                {% set my_sy = 3.00 %}
            {% elif row.partLocalName == "blade_left" or row.partLocalName == "blade_right" %}
                {% set my_ty = 8.193 %}
                {% set my_sy = 3.41 %}
            {% endif %}

            double3 xformOp:translate = ({{ row.translateX }}, {{ my_ty }}, {{ row.translateZ }})
            double3 xformOp:scale = ({{ row.scaleX }}, {{ my_sy }}, {{ row.scaleZ }})
            double3 xformOp:rotateXYZ = ({{ row.rotateX }}, {% if is_right %}-{{ row.rotateY }}{% else %}{{ row.rotateY }}{% endif %}, {% if is_right %}-{{ row.rotateZ }}{% else %}{{ row.rotateZ }}{% endif %})
            uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]

            {% if row.type == "angular_armor_shell" or row.type == "tapered_box" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_armor_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 0.5 - (i * 0.4 / row.density) }}, {{ 0.5 - (i * 0.4 / row.density) }}, 0.1)
                    double3 xformOp:translate = (0.0, 0.0, {{ i * 0.64 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Xform "hardpoint_{{ i }}"
                {
                    double3 xformOp:translate = (0.0, 0.0, {{ i * 0.64 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate"]
                }
                def Mesh "{{ row.primLocalName }}_armor_piston_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:translate = ({{ 0.4 - (i * 0.16 / row.density) }}, {{ 0.4 - (i * 0.16 / row.density) }}, {{ i * 0.64 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_armor_piston2_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:translate = ({{ -0.4 + (i * 0.16 / row.density) }}, {{ -0.4 + (i * 0.16 / row.density) }}, {{ i * 0.64 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% elif row.type == "layered_swept_feather_panel" or row.type == "feather_panel" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_feather_blade_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 0.8 - (i * 0.6 / row.density) }}, 0.05, {{ 1.5 - (i * 1.2 / row.density) }})
                    double3 xformOp:translate = ({% if is_right %}{{ i * 0.6 / row.density }}{% else %}-{{ i * 0.6 / row.density }}{% endif %}, {{ i * 0.6 / row.density }}, 0.0)
                    double3 xformOp:rotateXYZ = (0, {% if is_right %}{{ ((i % 2) * 360.0 / row.density) * -1.0 }}{% else %}{{ (i % 2) * 360.0 / row.density }}{% endif %}, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_feather_tip_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:translate = ({% if is_right %}{{ i * 0.6 / row.density }}{% else %}-{{ i * 0.6 / row.density }}{% endif %}, {{ i * 0.6 / row.density }}, 0.0)
                    double3 xformOp:rotateXYZ = (0, {% if is_right %}{{ ((i % 2) * 360.0 / row.density) * -1.0 }}{% else %}{{ (i % 2) * 360.0 / row.density }}{% endif %}, 0)
                    double3 xformOp:translate:tip = (0.0, 0.0, {{ 1.0 - (i * 0.6 / row.density) }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:translate:tip"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_GoldVisor>
                }
                {% endfor %}
            {% elif row.type == "beveled_hard_surface_plate" or row.type == "blade_prism" or row.type == "blade" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_beveled_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.8, 0.68, {{ 1.0 - (i * 0.75 / row.density) }})
                    double3 xformOp:translate = ({% if is_right %}{{ 0.9 + i * 0.225 / row.density }}{% else %}{{ -0.9 - i * 0.225 / row.density }}{% endif %}, {{ i * 0.0175 / row.density }}, 2.0)
                    double3 xformOp:rotateXYZ = (0, 0, {% if is_right %}4.5{% else %}-4.5{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_blade_edge_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    color3f[] primvars:displayColor = [(0, 1, 1)]
                    double3 xformOp:scale = (2.70, 0.1, 0.5)
                    double3 xformOp:translate = ({% if is_right %}0.9{% else %}-0.9{% endif %}, 0.0, 2.0)
                    double3 xformOp:rotateXYZ = (0, 0, {% if is_right %}4.5{% else %}-4.5{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_CyanBlade>
                }
                {% endfor %}
            {% elif row.type == "arm" %}
                def Mesh "{{ row.primLocalName }}_arm_inner_frame"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.3, 1.0, 0.3)
                    double3 xformOp:rotateXYZ = (90, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_arm_armor_shell_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.22, 0.08, 0.22)
                    double3 xformOp:translate = ({% if i % 4 == 0 %}0.12{% elif i % 4 == 1 %}-0.12{% elif i % 4 == 2 %}0.0{% else %}0.0{% endif %}, {{ (((i - (i % 4)) / 4) - 3) * 3.52 / row.density }}, {% if i % 4 == 2 %}0.12{% elif i % 4 == 3 %}-0.12{% else %}0.0{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_arm_panel_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.01, 0.85, 0.01)
                    double3 xformOp:translate = ({% if i % 4 == 0 %}0.23{% elif i % 4 == 1 %}-0.23{% elif i % 4 == 2 %}0.0{% else %}0.0{% endif %}, 0.0, {% if i % 4 == 2 %}0.23{% elif i % 4 == 3 %}-0.23{% else %}0.0{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_arm_horizontal_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.24, 0.015, 0.24)
                    double3 xformOp:translate = (0.0, {{ (((i - (i % 4)) / 4) - 3) * 3.52 / row.density + 1.76 / row.density }}, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% elif row.type == "leg" %}
                def Mesh "{{ row.primLocalName }}_leg_inner_frame"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.4, 1.2, 0.4)
                    double3 xformOp:rotateXYZ = (90, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_leg_armor_shell_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.3, 0.12, 0.3)
                    double3 xformOp:translate = ({% if i % 4 == 0 %}0.18{% elif i % 4 == 1 %}-0.18{% elif i % 4 == 2 %}0.0{% else %}0.0{% endif %}, {{ (((i - (i % 4)) / 4) - 3) * 4.48 / row.density }}, {% if i % 4 == 2 %}0.18{% elif i % 4 == 3 %}-0.18{% else %}0.0{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_leg_panel_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.02, 1.05, 0.02)
                    double3 xformOp:translate = ({% if i % 4 == 0 %}0.33{% elif i % 4 == 1 %}-0.33{% elif i % 4 == 2 %}0.0{% else %}0.0{% endif %}, 0.0, {% if i % 4 == 2 %}0.33{% elif i % 4 == 3 %}-0.33{% else %}0.0{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_leg_horizontal_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.32, 0.015, 0.32)
                    double3 xformOp:translate = (0.0, {{ (((i - (i % 4)) / 4) - 3) * 4.48 / row.density + 2.24 / row.density }}, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% elif row.type == "chest_armor" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_chest_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.6 - (i * 0.8 / row.density) }}, {{ 0.8 - (i * 0.4 / row.density) }}, 0.15)
                    double3 xformOp:translate = (0.0, {{ i * 0.6 / row.density }}, {{ 0.3 + (i * 0.4 / row.density) }})
                    double3 xformOp:rotateXYZ = (15, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "waist" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_waist_ring_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.2, 1.0, 0.2)
                    double3 xformOp:translate = (0.0, 0.0, {{ -0.5 + (i * 0.75 / row.density) }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% elif row.type == "abdomen" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_abdomen_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.4 - (i * 0.4 / row.density) }}, 0.8, 0.12)
                    double3 xformOp:translate = (0.0, 0.0, {{ -0.2 + (i * 0.6 / row.density) }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "inner_frame" %}
                def Mesh "{{ row.primLocalName }}_frame_core"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.0, 2.0, 0.5)
                    uniform token[] xformOpOrder = ["xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
            {% elif row.type == "helmet_armor" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_helmet_layer_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.4 - (i * 0.3 / row.density) }}, {{ 2.0 - (i * 0.6 / row.density) }}, {{ 0.6 - (i * 0.15 / row.density) }})
                    double3 xformOp:translate = (0.0, 0.0, {{ i * 0.15 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "cheek_guard" %}
                def Mesh "{{ row.primLocalName }}_guard_left"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.4, 0.8, 0.5)
                    double3 xformOp:translate = (-0.45, 0.2, -0.2)
                    double3 xformOp:rotateXYZ = (0, 15, -15)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_guard_right"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.4, 0.8, 0.5)
                    double3 xformOp:translate = (0.45, 0.2, -0.2)
                    double3 xformOp:rotateXYZ = (0, -15, 15)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "face_plate" %}
                def Mesh "{{ row.primLocalName }}_visor"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.0, 0.4, 0.25)
                    double3 xformOp:translate = (0.0, 0.45, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_GoldVisor>
                }
                def Mesh "{{ row.primLocalName }}_chin_guard"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.6, 0.6, 0.2)
                    double3 xformOp:translate = (0.0, 0.4, -0.35)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "neck_connection" %}
                def Mesh "{{ row.primLocalName }}_neck_collar"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.8, 0.8, 0.4)
                    double3 xformOp:translate = (0.0, -0.6, -0.4)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
            {% elif row.type == "pauldron" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_pauldron_layer_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.8 - (i * 0.6 / row.density) }}, {{ 2.0 - (i * 0.6 / row.density) }}, {{ 0.5 - (i * 0.15 / row.density) }})
                    double3 xformOp:translate = ({% if is_right %}-{{ i * 0.3 / row.density }}{% else %}{{ i * 0.3 / row.density }}{% endif %}, 0.0, {{ i * 0.45 / row.density }})
                    double3 xformOp:rotateXYZ = (0, {% if is_right %}-15{% else %}15{% endif %}, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "shield_mount" %}
                def Mesh "{{ row.primLocalName }}_mount"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "shield_handle" %}
                def Mesh "{{ row.primLocalName }}_handle"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "shield_frame" %}
                def Mesh "{{ row.primLocalName }}_frame"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "shield_rim" %}
                def Mesh "{{ row.primLocalName }}_rim"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "shield_plate" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_plate_layer_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.0 - (i * 0.6 / row.density) }}, {{ 1.0 - (i * 0.45 / row.density) }}, {{ 1.0 - (i * 0.45 / row.density) }})
                    double3 xformOp:translate = ({{ i * 0.3 / row.density }}, 0.0, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "core" or row.type == "hard_surface_shell" %}
                def Mesh "{{ row.primLocalName }}_core_inner_frame"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.2, 2.0, 0.8)
                    uniform token[] xformOpOrder = ["xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_core_armor_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.35, 0.02, 0.1)
                    double3 xformOp:translate = (0.0, {{ (i - row.density / 2) * 1.6 / row.density }}, 0.3)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_core_panel_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.02, 0.04, 0.12)
                    double3 xformOp:translate = ({% if i % 2 == 0 %}0.1{% else %}-0.1{% endif %}, {{ (i - row.density / 2) * 1.6 / row.density }}, 0.3)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_core_horizontal_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.37, 0.005, 0.11)
                    double3 xformOp:translate = (0.0, {{ (i - row.density / 2) * 1.6 / row.density + 0.8 / row.density }}, 0.3)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% else %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_subframe_core_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    double3 xformOp:scale = (0.2, 0.5, 0.2)
                    double3 xformOp:translate = ({% if is_right %}0.4{% else %}-0.4{% endif %}, 0.0, 0.0)
                    double3 xformOp:rotateXYZ = (90, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_subframe_joint_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.2, 0.2, 0.2)
                    double3 xformOp:translate = ({% if is_right %}0.4{% else %}-0.4{% endif %}, {{ 0.4 + (i * 0.3 / row.density) }}, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% endif %}
        }
    {% endif %}
{% endmacro %}"""

# Join back
new_content = parts_before[0] + new_part_mesh_tera + parts_after[0] + end_token + parts_after[1]

with open(py_path, "w") as f:
    f.write(new_content)

print("Successfully patched patch_geometry_generator.py template!")
