import os
import json
import rdflib

# 0. Validate required graph facts exist in all_merged.ttl
merged_ttl = "/Users/sac/rocket-craft/ontology/all_merged.ttl"
if os.path.exists(merged_ttl):
    g = rdflib.Graph()
    try:
        g.parse(merged_ttl, format="turtle")
        print(f"Loaded all_merged.ttl with {len(g)} triples for verification.")
        
        # Check that we have GeometryPrimitives
        MUD = rdflib.Namespace("https://rocket-craft.com/ontology/mud#")
        LAW = rdflib.Namespace("https://rocket-craft.com/ontology/law#")
        prims = list(g.subjects(rdflib.RDF.type, MUD.GeometryPrimitive))
        if not prims:
            raise ValueError("No GeometryPrimitive objects found in the merged graph!")
        
        # Validate that each primitive has required morphology attributes
        for prim in prims:
            tys = list(g.objects(prim, MUD.translateY))
            sys_ = list(g.objects(prim, MUD.scaleY))
            densities = list(g.objects(prim, LAW.hasSubdivisionDensity))
            mats = list(g.objects(prim, LAW.hasMaterialZoneBinding))
            
            if not tys:
                raise ValueError(f"Primitive {prim} is missing mud:translateY")
            if not sys_:
                raise ValueError(f"Primitive {prim} is missing mud:scaleY")
            if not densities:
                raise ValueError(f"Primitive {prim} is missing law:hasSubdivisionDensity")
            if not mats:
                raise ValueError(f"Primitive {prim} is missing law:hasMaterialZoneBinding")
                
        print("Successfully validated all required graph facts in all_merged.ttl.")
    except Exception as e:
        print(f"Graph validation failed: {e}")
        raise e
else:
    print("Warning: all_merged.ttl not found yet, skipping validation during bootstrap.")

base_dir = "/Users/sac/rocket-craft/generated/mech_assets/reference_fabric_001"
os.makedirs(f"{base_dir}/templates/usd", exist_ok=True)
os.makedirs(f"{base_dir}/templates/materialx", exist_ok=True)
os.makedirs(f"{base_dir}/usd", exist_ok=True)
os.makedirs(f"{base_dir}/materialx", exist_ok=True)
os.makedirs(f"{base_dir}/textures", exist_ok=True)

# 1. Write part_mesh.usda.tera
part_mesh_tera = """#usda 1.0
(
{% set has_torso = false %}
{% set has_head = false %}
{% set has_wing_left = false %}
{% set has_wing_right = false %}
{% set has_blade_left = false %}
{% set has_blade_right = false %}
{% set has_limb_left = false %}
{% set has_limb_right = false %}
{% set has_loadout = false %}

{% for row in results %}
    {% if row.partLocalName == "torso_core" %}
        {% set_global has_torso = true %}
    {% elif row.partLocalName == "head_unit" or row.partLocalName == "v_fin_left" or row.partLocalName == "v_fin_right" %}
        {% set_global has_head = true %}
    {% elif row.partLocalName == "wing_root_left" or row.partLocalName == "primary_wing_feathers_left" or row.partLocalName == "secondary_wing_feathers_left" %}
        {% set_global has_wing_left = true %}
    {% elif row.partLocalName == "wing_root_right" or row.partLocalName == "primary_wing_feathers_right" or row.partLocalName == "secondary_wing_feathers_right" %}
        {% set_global has_wing_right = true %}
    {% elif row.partLocalName == "blade_left" %}
        {% set_global has_blade_left = true %}
    {% elif row.partLocalName == "blade_right" %}
        {% set_global has_blade_right = true %}
    {% elif row.partLocalName == "shoulder_left" or row.partLocalName == "arm_left" or row.partLocalName == "leg_left" %}
        {% set_global has_limb_left = true %}
    {% elif row.partLocalName == "shoulder_right" or row.partLocalName == "arm_right" or row.partLocalName == "leg_right" %}
        {% set_global has_limb_right = true %}
    {% elif row.partLocalName == "backpack_core" or row.partLocalName == "thruster_cluster" %}
        {% set_global has_loadout = true %}
    {% endif %}
{% endfor %}

{% if has_torso %}
    defaultPrim = "SM_Torso"
{% elif has_head %}
    defaultPrim = "SM_Head"
{% elif has_wing_left %}
    defaultPrim = "SM_WingArray_Left"
{% elif has_wing_right %}
    defaultPrim = "SM_WingArray_Right"
{% elif has_blade_left %}
    defaultPrim = "SM_Blade_Left"
{% elif has_blade_right %}
    defaultPrim = "SM_Blade_Right"
{% elif has_limb_left %}
    defaultPrim = "SM_Limb_Left"
{% elif has_limb_right %}
    defaultPrim = "SM_Limb_Right"
{% elif has_loadout %}
    defaultPrim = "SM_Loadout"
{% else %}
    defaultPrim = "SM_Unknown"
{% endif %}
    upAxis = "Y"
    metersPerUnit = 0.01
    doc = "Generated by ggen. Deterministic USD StaticMesh container."
)

{% macro render_primitive(row, is_right) %}
    {% if row.type == "socket" %}
        def Xform "{{ row.primLocalName }}"
        {
            double3 xformOp:translate = ({{ row.translateX }}, {{ row.translateY }}, {{ row.translateZ }})
            uniform token[] xformOpOrder = ["xformOp:translate"]
        }
    {% else %}
        def Xform "{{ row.primLocalName }}_group"
        {
            double3 xformOp:translate = ({{ row.translateX }}, {{ row.translateY }}, {{ row.translateZ }})
            double3 xformOp:scale = ({{ row.scaleX }}, {{ row.scaleY }}, {{ row.scaleZ }})
            double3 xformOp:rotateXYZ = ({{ row.rotateX }}, {% if is_right %}-{{ row.rotateY }}{% else %}{{ row.rotateY }}{% endif %}, {% if is_right %}-{{ row.rotateZ }}{% else %}{{ row.rotateZ }}{% endif %})
            uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]

            {% if row.type == "angular_armor_shell" or row.type == "tapered_box" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_armor_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 0.5 - (i * 0.4 / row.density) }}, {{ 0.5 - (i * 0.4 / row.density) }}, 0.1)
                    double3 xformOp:translate = (0.0, 0.0, {{ i * 0.64 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Xform "hardpoint_{{ i }}"
                {
                    double3 xformOp:translate = (0.0, 0.0, {{ i * 0.64 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate"]
                }
                def Mesh "{{ row.primLocalName }}_armor_piston_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:translate = ({{ 0.4 - (i * 0.16 / row.density) }}, {{ 0.4 - (i * 0.16 / row.density) }}, {{ i * 0.64 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_armor_piston2_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:translate = ({{ -0.4 + (i * 0.16 / row.density) }}, {{ -0.4 + (i * 0.16 / row.density) }}, {{ i * 0.64 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% elif row.type == "layered_swept_feather_panel" or row.type == "feather_panel" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_feather_blade_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 0.8 - (i * 0.6 / row.density) }}, 0.05, {{ 1.5 - (i * 1.2 / row.density) }})
                    double3 xformOp:translate = ({% if is_right %}{{ i * 0.6 / row.density }}{% else %}-{{ i * 0.6 / row.density }}{% endif %}, {{ i * 0.6 / row.density }}, 0.0)
                    double3 xformOp:rotateXYZ = (0, {% if is_right %}{{ ((i % 2) * 360.0 / row.density) * -1.0 }}{% else %}{{ (i % 2) * 360.0 / row.density }}{% endif %}, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_feather_tip_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:translate = ({% if is_right %}{{ i * 0.6 / row.density }}{% else %}-{{ i * 0.6 / row.density }}{% endif %}, {{ i * 0.6 / row.density }}, 0.0)
                    double3 xformOp:rotateXYZ = (0, {% if is_right %}{{ ((i % 2) * 360.0 / row.density) * -1.0 }}{% else %}{{ (i % 2) * 360.0 / row.density }}{% endif %}, 0)
                    double3 xformOp:translate:tip = (0.0, 0.0, {{ 1.0 - (i * 0.6 / row.density) }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:translate:tip"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_GoldVisor>
                }
                {% endfor %}
            {% elif row.type == "beveled_hard_surface_plate" or row.type == "blade_prism" or row.type == "blade" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_beveled_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.8, 0.68, {{ 1.0 - (i * 0.75 / row.density) }})
                    double3 xformOp:translate = ({% if is_right %}{{ 0.9 + i * 0.225 / row.density }}{% else %}{{ -0.9 - i * 0.225 / row.density }}{% endif %}, {{ i * 0.0175 / row.density }}, 2.0)
                    double3 xformOp:rotateXYZ = (0, 0, {% if is_right %}4.5{% else %}-4.5{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_blade_edge_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    color3f[] primvars:displayColor = [(0, 1, 1)]
                    double3 xformOp:scale = (2.70, 0.1, 0.5)
                    double3 xformOp:translate = ({% if is_right %}0.9{% else %}-0.9{% endif %}, 0.0, 2.0)
                    double3 xformOp:rotateXYZ = (0, 0, {% if is_right %}4.5{% else %}-4.5{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_CyanBlade>
                }
                {% endfor %}
            {% elif row.type == "arm" %}
                def Mesh "{{ row.primLocalName }}_arm_inner_frame"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.3, 1.0, 0.3)
                    double3 xformOp:rotateXYZ = (90, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_arm_armor_shell_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.22, 0.08, 0.22)
                    double3 xformOp:translate = ({% if i % 4 == 0 %}0.12{% elif i % 4 == 1 %}-0.12{% elif i % 4 == 2 %}0.0{% else %}0.0{% endif %}, {{ (((i - (i % 4)) / 4) - 3) * 3.52 / row.density }}, {% if i % 4 == 2 %}0.12{% elif i % 4 == 3 %}-0.12{% else %}0.0{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_arm_panel_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.01, 0.85, 0.01)
                    double3 xformOp:translate = ({% if i % 4 == 0 %}0.23{% elif i % 4 == 1 %}-0.23{% elif i % 4 == 2 %}0.0{% else %}0.0{% endif %}, 0.0, {% if i % 4 == 2 %}0.23{% elif i % 4 == 3 %}-0.23{% else %}0.0{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_arm_horizontal_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.24, 0.015, 0.24)
                    double3 xformOp:translate = (0.0, {{ (((i - (i % 4)) / 4) - 3) * 3.52 / row.density + 1.76 / row.density }}, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% elif row.type == "leg" %}
                def Mesh "{{ row.primLocalName }}_leg_inner_frame"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.4, 1.2, 0.4)
                    double3 xformOp:rotateXYZ = (90, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_leg_armor_shell_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.3, 0.12, 0.3)
                    double3 xformOp:translate = ({% if i % 4 == 0 %}0.18{% elif i % 4 == 1 %}-0.18{% elif i % 4 == 2 %}0.0{% else %}0.0{% endif %}, {{ (((i - (i % 4)) / 4) - 3) * 4.48 / row.density }}, {% if i % 4 == 2 %}0.18{% elif i % 4 == 3 %}-0.18{% else %}0.0{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_leg_panel_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.02, 1.05, 0.02)
                    double3 xformOp:translate = ({% if i % 4 == 0 %}0.33{% elif i % 4 == 1 %}-0.33{% elif i % 4 == 2 %}0.0{% else %}0.0{% endif %}, 0.0, {% if i % 4 == 2 %}0.33{% elif i % 4 == 3 %}-0.33{% else %}0.0{% endif %})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_leg_horizontal_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.32, 0.015, 0.32)
                    double3 xformOp:translate = (0.0, {{ (((i - (i % 4)) / 4) - 3) * 4.48 / row.density + 2.24 / row.density }}, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% elif row.type == "chest_armor" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_chest_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.6 - (i * 0.8 / row.density) }}, {{ 0.8 - (i * 0.4 / row.density) }}, 0.15)
                    double3 xformOp:translate = (0.0, {{ i * 0.6 / row.density }}, {{ 0.3 + (i * 0.4 / row.density) }})
                    double3 xformOp:rotateXYZ = (15, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "waist" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_waist_ring_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.2, 1.0, 0.2)
                    double3 xformOp:translate = (0.0, 0.0, {{ -0.5 + (i * 0.75 / row.density) }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% elif row.type == "abdomen" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_abdomen_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.4 - (i * 0.4 / row.density) }}, 0.8, 0.12)
                    double3 xformOp:translate = (0.0, 0.0, {{ -0.2 + (i * 0.6 / row.density) }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "inner_frame" %}
                def Mesh "{{ row.primLocalName }}_frame_core"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.0, 2.0, 0.5)
                    uniform token[] xformOpOrder = ["xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
            {% elif row.type == "helmet_armor" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_helmet_layer_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.4 - (i * 0.3 / row.density) }}, {{ 2.0 - (i * 0.6 / row.density) }}, {{ 0.6 - (i * 0.15 / row.density) }})
                    double3 xformOp:translate = (0.0, 0.0, {{ i * 0.15 / row.density }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "cheek_guard" %}
                def Mesh "{{ row.primLocalName }}_guard_left"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.4, 0.8, 0.5)
                    double3 xformOp:translate = (-0.45, 0.2, -0.2)
                    double3 xformOp:rotateXYZ = (0, 15, -15)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_guard_right"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.4, 0.8, 0.5)
                    double3 xformOp:translate = (0.45, 0.2, -0.2)
                    double3 xformOp:rotateXYZ = (0, -15, 15)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "face_plate" %}
                def Mesh "{{ row.primLocalName }}_visor"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.0, 0.4, 0.25)
                    double3 xformOp:translate = (0.0, 0.45, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_GoldVisor>
                }
                def Mesh "{{ row.primLocalName }}_chin_guard"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.6, 0.6, 0.2)
                    double3 xformOp:translate = (0.0, 0.4, -0.35)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "neck_connection" %}
                def Mesh "{{ row.primLocalName }}_neck_collar"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.8, 0.8, 0.4)
                    double3 xformOp:translate = (0.0, -0.6, -0.4)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
            {% elif row.type == "pauldron" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_pauldron_layer_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.8 - (i * 0.6 / row.density) }}, {{ 2.0 - (i * 0.6 / row.density) }}, {{ 0.5 - (i * 0.15 / row.density) }})
                    double3 xformOp:translate = ({% if is_right %}-{{ i * 0.3 / row.density }}{% else %}{{ i * 0.3 / row.density }}{% endif %}, 0.0, {{ i * 0.45 / row.density }})
                    double3 xformOp:rotateXYZ = (0, {% if is_right %}-15{% else %}15{% endif %}, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "shield_mount" %}
                def Mesh "{{ row.primLocalName }}_mount"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "shield_handle" %}
                def Mesh "{{ row.primLocalName }}_handle"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "shield_frame" %}
                def Mesh "{{ row.primLocalName }}_frame"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "shield_rim" %}
                def Mesh "{{ row.primLocalName }}_rim"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
            {% elif row.type == "shield_plate" %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_plate_layer_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = ({{ 1.0 - (i * 0.6 / row.density) }}, {{ 1.0 - (i * 0.45 / row.density) }}, {{ 1.0 - (i * 0.45 / row.density) }})
                    double3 xformOp:translate = ({{ i * 0.3 / row.density }}, 0.0, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% elif row.type == "core" or row.type == "hard_surface_shell" %}
                def Mesh "{{ row.primLocalName }}_core_inner_frame"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (1.2, 2.0, 0.8)
                    uniform token[] xformOpOrder = ["xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_core_armor_plate_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.35, 0.02, 0.1)
                    double3 xformOp:translate = (0.0, {{ (i - row.density / 2) * 1.6 / row.density }}, 0.3)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                def Mesh "{{ row.primLocalName }}_core_panel_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.02, 0.04, 0.12)
                    double3 xformOp:translate = ({% if i % 2 == 0 %}0.1{% else %}-0.1{% endif %}, {{ (i - row.density / 2) * 1.6 / row.density }}, 0.3)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_core_horizontal_split_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.37, 0.005, 0.11)
                    double3 xformOp:translate = (0.0, {{ (i - row.density / 2) * 1.6 / row.density + 0.8 / row.density }}, 0.3)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% else %}
                {% for i in range(end=row.density) %}
                def Mesh "{{ row.primLocalName }}_subframe_core_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    double3 xformOp:scale = (0.2, 0.5, 0.2)
                    double3 xformOp:translate = ({% if is_right %}0.4{% else %}-0.4{% endif %}, 0.0, 0.0)
                    double3 xformOp:rotateXYZ = (90, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Mesh "{{ row.primLocalName }}_subframe_joint_{{ i }}"
                {
                    int[] faceVertexCounts = [6, 6, 4, 4, 4, 4, 4, 4]
                    int[] faceVertexIndices = [5, 4, 3, 2, 1, 0, 6, 7, 8, 9, 10, 11, 0, 1, 7, 6, 1, 2, 8, 7, 2, 3, 9, 8, 3, 4, 10, 9, 4, 5, 11, 10, 5, 0, 6, 11]
                    point3f[] points = [(0.5, 0.0, -0.5), (0.25, 0.5, -0.5), (-0.25, 0.5, -0.5), (-0.5, 0.0, -0.5), (-0.25, -0.5, -0.5), (0.25, -0.5, -0.5), (0.5, 0.0, 0.5), (0.25, 0.5, 0.5), (-0.25, 0.5, 0.5), (-0.5, 0.0, 0.5), (-0.25, -0.5, 0.5), (0.25, -0.5, 0.5)]
                    uniform token subdivisionScheme = "none"
                    double3 xformOp:scale = (0.2, 0.2, 0.2)
                    double3 xformOp:translate = ({% if is_right %}0.4{% else %}-0.4{% endif %}, {{ 0.4 + (i * 0.3 / row.density) }}, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.matZoneLocalName }}>
                }
                {% endfor %}
            {% endif %}
        }
    {% endif %}
{% endmacro %}
(
{% set has_torso = false %}
{% set has_head = false %}
{% set has_wing_left = false %}
{% set has_wing_right = false %}
{% set has_blade_left = false %}
{% set has_blade_right = false %}
{% set has_limb_left = false %}
{% set has_limb_right = false %}
{% set has_loadout = false %}

{% for row in results %}
    {% if row.partLocalName == "torso_core" %}
        {% set_global has_torso = true %}
    {% elif row.partLocalName == "head_unit" or row.partLocalName == "v_fin_left" or row.partLocalName == "v_fin_right" %}
        {% set_global has_head = true %}
    {% elif row.partLocalName == "wing_root_left" or row.partLocalName == "primary_wing_feathers_left" or row.partLocalName == "secondary_wing_feathers_left" %}
        {% set_global has_wing_left = true %}
    {% elif row.partLocalName == "wing_root_right" or row.partLocalName == "primary_wing_feathers_right" or row.partLocalName == "secondary_wing_feathers_right" %}
        {% set_global has_wing_right = true %}
    {% elif row.partLocalName == "blade_left" %}
        {% set_global has_blade_left = true %}
    {% elif row.partLocalName == "blade_right" %}
        {% set_global has_blade_right = true %}
    {% elif row.partLocalName == "shoulder_left" or row.partLocalName == "arm_left" or row.partLocalName == "leg_left" %}
        {% set_global has_limb_left = true %}
    {% elif row.partLocalName == "shoulder_right" or row.partLocalName == "arm_right" or row.partLocalName == "leg_right" %}
        {% set_global has_limb_right = true %}
    {% elif row.partLocalName == "backpack_core" or row.partLocalName == "thruster_cluster" %}
        {% set_global has_loadout = true %}
    {% endif %}
{% endfor %}

{% if has_torso %}
    defaultPrim = "SM_Torso"
{% elif has_head %}
    defaultPrim = "SM_Head"
{% elif has_wing_left %}
    defaultPrim = "SM_WingArray_Left"
{% elif has_wing_right %}
    defaultPrim = "SM_WingArray_Right"
{% elif has_blade_left %}
    defaultPrim = "SM_Blade_Left"
{% elif has_blade_right %}
    defaultPrim = "SM_Blade_Right"
{% elif has_limb_left %}
    defaultPrim = "SM_Limb_Left"
{% elif has_limb_right %}
    defaultPrim = "SM_Limb_Right"
{% elif has_loadout %}
    defaultPrim = "SM_Loadout"
{% else %}
    defaultPrim = "SM_Unknown"
{% endif %}
    upAxis = "Y"
    metersPerUnit = 0.01
    doc = "Generated by ggen. Deterministic USD StaticMesh container."
)

{% macro render_primitive(row, is_right) %}
    {% if row.type == "socket" %}
        def Xform "{{ row.primLocalName }}"
        {
            double3 xformOp:translate = ({{ row.translateX }}, {{ row.translateY }}, {{ row.translateZ }})
            uniform token[] xformOpOrder = ["xformOp:translate"]
        }
    {% else %}
        def Xform "{{ row.primLocalName }}_group"
        {
            point3f[] points = [(0, 0, 0)]
            {% if is_right %}
            double3 xformOp:translate = (-{{ row.translateX }}, {{ row.translateY }}, {{ row.translateZ }})
            {% else %}
            double3 xformOp:translate = ({{ row.translateX }}, {{ row.translateY }}, {{ row.translateZ }})
            {% endif %}
            double3 xformOp:scale = ({{ row.scaleX }}, {{ row.scaleY }}, {{ row.scaleZ }})
            double3 xformOp:rotateXYZ = ({{ row.rotateX }}, {{ row.rotateY }}, {{ row.rotateZ }})
            uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]

            {% if row.type == "angular_armor_shell" or row.type == "tapered_box" %}
                {% for i in range(end=8) %}
                def Cube "armor_plate_{{ i }}"
                {
                    double size = 1.0
                    double3 xformOp:scale = ({{ 1.0 - (i * 0.05) }}, {{ 1.0 - (i * 0.05) }}, 0.1)
                    double3 xformOp:translate = (0.0, 0.0, {{ i * 0.08 }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.materialLocalName }}>
                }
                def Xform "hardpoint_{{ i }}"
                {
                    double3 xformOp:translate = (0.0, 0.0, {{ i * 0.08 }})
                    uniform token[] xformOpOrder = ["xformOp:translate"]
                }
                def Cylinder "armor_piston_{{ i }}"
                {
                    double radius = 0.05
                    double height = 1.2
                    double3 xformOp:translate = ({{ 0.4 - (i * 0.02) }}, {{ 0.4 - (i * 0.02) }}, {{ i * 0.08 }})
                    uniform token[] xformOpOrder = ["xformOp:translate"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Cylinder "armor_piston2_{{ i }}"
                {
                    double radius = 0.05
                    double height = 1.2
                    double3 xformOp:translate = ({{ -0.4 + (i * 0.02) }}, {{ -0.4 + (i * 0.02) }}, {{ i * 0.08 }})
                    uniform token[] xformOpOrder = ["xformOp:translate"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                {% endfor %}
            {% elif row.type == "layered_swept_feather_panel" or row.type == "feather_panel" %}
                {% for i in range(end=12) %}
                def Cube "feather_blade_{{ i }}"
                {
                    double size = 1.0
                    double3 xformOp:scale = ({{ 0.8 - (i * 0.05) }}, 0.05, {{ 1.5 - (i * 0.1) }})
                    double3 xformOp:translate = ({{ i * 0.1 }}, {{ i * 0.05 }}, 0.0)
                    double3 xformOp:rotateXYZ = (0, {{ i * 10.0 }}, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.materialLocalName }}>
                }
                def Cone "feather_tip_{{ i }}"
                {
                    double radius = 0.2
                    double height = 0.5
                    double3 xformOp:translate = ({{ i * 0.1 }}, {{ i * 0.05 }}, 0.0)
                    double3 xformOp:rotateXYZ = (0, {{ i * 10.0 }}, 0)
                    double3 xformOp:translate:tip = (0.0, 0.0, {{ 1.0 - (i * 0.05) }})
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:translate:tip"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_CyanBlade>
                }
                {% endfor %}
            {% elif row.type == "beveled_hard_surface_plate" or row.type == "blade_prism" %}
                {% for i in range(end=5) %}
                def Cube "beveled_plate_{{ i }}"
                {
                    double size = 1.0
                    double3 xformOp:scale = (0.6, 0.2, {{ 1.0 - (i * 0.15) }})
                    double3 xformOp:translate = (0.0, {{ i * 0.05 }}, 0.0)
                    double3 xformOp:rotateXYZ = ({{ i * 5.0 }}, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.materialLocalName }}>
                }
                def Capsule "blade_edge_{{ i }}"
                {
                    double radius = 0.02
                    double height = {{ 1.0 - (i * 0.15) }}
                    double3 xformOp:translate = (0.3, {{ i * 0.05 }}, 0.0)
                    double3 xformOp:rotateXYZ = ({{ i * 5.0 }}, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_CyanBlade>
                }
                {% endfor %}
            {% else %}
                {% for i in range(end=6) %}
                def Cylinder "subframe_core_{{ i }}"
                {
                    double radius = {{ 0.3 - (i * 0.04) }}
                    double height = {{ 0.8 + (i * 0.1) }}
                    double3 xformOp:rotateXYZ = (90, 0, 0)
                    uniform token[] xformOpOrder = ["xformOp:rotateXYZ"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/M_DarkFrame>
                }
                def Sphere "subframe_joint_{{ i }}"
                {
                    double radius = 0.35
                    double3 xformOp:scale = (1.0, 0.5, 1.0)
                    double3 xformOp:translate = (0.0, {{ 0.4 + (i * 0.05) }}, 0.0)
                    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
                    rel material:binding = </ASSET_ReferenceFabric_001/Materials/{{ row.materialLocalName }}>
                }
                {% endfor %}
            {% endif %}
        }
    {% endif %}
{% endmacro %}

{% if has_torso %}
def Xform "SM_Torso"
{
    custom string owner_part_id = "SM_Torso"
    {% for row in results %}
        {% if row.partLocalName == "torso_core" %}
            {{ self::render_primitive(row=row, is_right=false) }}
        {% endif %}
    {% endfor %}
}
{% endif %}

{% if has_head %}
def Xform "SM_Head"
{
    custom string owner_part_id = "SM_Head"
    {% for row in results %}
        {% if row.partLocalName == "head_unit" or row.partLocalName == "v_fin_left" or row.partLocalName == "v_fin_right" %}
            {{ self::render_primitive(row=row, is_right=false) }}
        {% endif %}
    {% endfor %}
}
{% endif %}

{% if has_wing_left %}
def Xform "SM_WingArray_Left"
{
    custom string owner_part_id = "SM_WingArray_Left"
    {% for row in results %}
        {% if row.partLocalName == "wing_root_left" or row.partLocalName == "primary_wing_feathers_left" or row.partLocalName == "secondary_wing_feathers_left" %}
            {{ self::render_primitive(row=row, is_right=false) }}
        {% endif %}
    {% endfor %}
}
{% endif %}

{% if has_wing_right %}
def Xform "SM_WingArray_Right"
{
    custom string owner_part_id = "SM_WingArray_Right"
    {% for row in results %}
        {% if row.partLocalName == "wing_root_right" or row.partLocalName == "primary_wing_feathers_right" or row.partLocalName == "secondary_wing_feathers_right" %}
            {{ self::render_primitive(row=row, is_right=true) }}
        {% endif %}
    {% endfor %}
}
{% endif %}

{% if has_blade_left %}
def Xform "SM_Blade_Left"
{
    custom string owner_part_id = "SM_Blade_Left"
    {% for row in results %}
        {% if row.partLocalName == "blade_left" %}
            {{ self::render_primitive(row=row, is_right=false) }}
        {% endif %}
    {% endfor %}
}
{% endif %}

{% if has_blade_right %}
def Xform "SM_Blade_Right"
{
    custom string owner_part_id = "SM_Blade_Right"
    {% for row in results %}
        {% if row.partLocalName == "blade_right" %}
            {{ self::render_primitive(row=row, is_right=true) }}
        {% endif %}
    {% endfor %}
}
{% endif %}

{% if has_limb_left %}
def Xform "SM_Limb_Left"
{
    custom string owner_part_id = "SM_Limb_Left"
    {% for row in results %}
        {% if row.partLocalName == "shoulder_left" or row.partLocalName == "arm_left" or row.partLocalName == "leg_left" %}
            {{ self::render_primitive(row=row, is_right=false) }}
        {% endif %}
    {% endfor %}
}
{% endif %}

{% if has_limb_right %}
def Xform "SM_Limb_Right"
{
    custom string owner_part_id = "SM_Limb_Right"
    {% for row in results %}
        {% if row.partLocalName == "shoulder_right" or row.partLocalName == "arm_right" or row.partLocalName == "leg_right" %}
            {{ self::render_primitive(row=row, is_right=true) }}
        {% endif %}
    {% endfor %}
}
{% endif %}

{% if has_loadout %}
def Xform "SM_Loadout"
{
    custom string owner_part_id = "SM_Loadout"
    {% for row in results %}
        {% if row.partLocalName == "backpack_core" or row.partLocalName == "thruster_cluster" %}
            {{ self::render_primitive(row=row, is_right=false) }}
        {% endif %}
    {% endfor %}
}
{% endif %}
"""

with open(f"{base_dir}/templates/usd/part_mesh.usda.tera", "w") as f:
    f.write(part_mesh_tera)

# 2. Write asset.usda.tera
asset_tera = """#usda 1.0
(
    defaultPrim = "ASSET_ReferenceFabric_001"
    upAxis = "Y"
    metersPerUnit = 0.01
)

def Xform "ASSET_ReferenceFabric_001"
{
    def Xform "Torso" (
        prepend references = @./SM_Torso.usda@
    )
    {
    }

    def Xform "Head" (
        prepend references = @./SM_Head.usda@
    )
    {
    }

    def Xform "Wing_Left" (
        prepend references = @./SM_WingArray_Left.usda@
    )
    {
    }

    def Xform "Wing_Right" (
        prepend references = @./SM_WingArray_Right.usda@
    )
    {
    }

    def Xform "Blade_Left" (
        prepend references = @./SM_Blade_Left.usda@
    )
    {
    }

    def Xform "Blade_Right" (
        prepend references = @./SM_Blade_Right.usda@
    )
    {
    }

    def Xform "Limb_Left" (
        prepend references = @./SM_Limb_Left.usda@
    )
    {
    }

    def Xform "Limb_Right" (
        prepend references = @./SM_Limb_Right.usda@
    )
    {
    }

    def Xform "Loadout" (
        prepend references = @./SM_Loadout.usda@
    )
    {
    }

    def Scope "Materials"
    {
        {% for row in results %}
        def Material "{{ row.materialLocalName }}" (
            prepend references = @../materialx/{{ row.materialLocalName }}.mtlx@
        )
        {
        }
        {% endfor %}
    }
}
"""

with open(f"{base_dir}/templates/usd/asset.usda.tera", "w") as f:
    f.write(asset_tera)

# 3. Write materialx.mtlx.tera
mtlx_tera = """<?xml version="1.0"?>
<materialx version="1.38">
  <nodegraph name="NG_Armor">
    <!-- ... -->
  </nodegraph>
</materialx>
"""
with open(f"{base_dir}/templates/materialx/materials.mtlx.tera", "w") as f:
    f.write(mtlx_tera)

# 4. Modify ggen.toml to include the missing rules
import re
with open("/Users/sac/rocket-craft/ggen.toml", "r") as f:
    ggen_content = f.read()

limb_left_rule = """
[[generation.rules]]
name = "SM_Limb_Left"
query = { inline = '''
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mud: <https://rocket-craft.com/ontology/mud#>
SELECT ?prim ?part ?type ?translateX ?translateY ?translateZ ?scaleX ?scaleY ?scaleZ ?rotateX ?rotateY ?rotateZ ?materialBinding ?partLocalName ?materialLocalName ?primLocalName
WHERE {
  VALUES (?CURRENT_PART_ID) {
    (mud:shoulder_left) (mud:arm_left) (mud:leg_left)
  }
  ?prim rdf:type mud:GeometryPrimitive ;
        mud:belongsToPart ?CURRENT_PART_ID ;
        mud:belongsToPart ?part ;
        mud:primitiveFamily ?type ;
        mud:translateX ?translateX ;
        mud:translateY ?translateY ;
        mud:translateZ ?translateZ ;
        mud:scaleX ?scaleX ;
        mud:scaleY ?scaleY ;
        mud:scaleZ ?scaleZ ;
        mud:rotateX ?rotateX ;
        mud:rotateY ?rotateY ;
        mud:rotateZ ?rotateZ ;
        mud:materialBinding ?materialBinding .
  BIND(STRAFTER(STR(?part), "#") AS ?partLocalName)
  BIND(STRAFTER(STR(?materialBinding), "#") AS ?materialLocalName)
  BIND(STRAFTER(STR(?prim), "#") AS ?primLocalName)
}
ORDER BY ?prim
''' }
mode = "Overwrite"
template = { file = "generated/mech_assets/reference_fabric_001/templates/usd/part_mesh.usda.tera" }
output_file = "generated/mech_assets/reference_fabric_001/usd/SM_Limb_Left.usda"
"""

limb_right_rule = """
[[generation.rules]]
name = "SM_Limb_Right"
query = { inline = '''
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mud: <https://rocket-craft.com/ontology/mud#>
SELECT ?prim ?part ?type ?translateX ?translateY ?translateZ ?scaleX ?scaleY ?scaleZ ?rotateX ?rotateY ?rotateZ ?materialBinding ?partLocalName ?materialLocalName ?primLocalName
WHERE {
  VALUES (?CURRENT_PART_ID) {
    (mud:shoulder_right) (mud:arm_right) (mud:leg_right)
  }
  ?prim rdf:type mud:GeometryPrimitive ;
        mud:belongsToPart ?CURRENT_PART_ID ;
        mud:belongsToPart ?part ;
        mud:primitiveFamily ?type ;
        mud:translateX ?translateX ;
        mud:translateY ?translateY ;
        mud:translateZ ?translateZ ;
        mud:scaleX ?scaleX ;
        mud:scaleY ?scaleY ;
        mud:scaleZ ?scaleZ ;
        mud:rotateX ?rotateX ;
        mud:rotateY ?rotateY ;
        mud:rotateZ ?rotateZ ;
        mud:materialBinding ?materialBinding .
  BIND(STRAFTER(STR(?part), "#") AS ?partLocalName)
  BIND(STRAFTER(STR(?materialBinding), "#") AS ?materialLocalName)
  BIND(STRAFTER(STR(?prim), "#") AS ?primLocalName)
}
ORDER BY ?prim
''' }
mode = "Overwrite"
template = { file = "generated/mech_assets/reference_fabric_001/templates/usd/part_mesh.usda.tera" }
output_file = "generated/mech_assets/reference_fabric_001/usd/SM_Limb_Right.usda"
"""

loadout_rule = """
[[generation.rules]]
name = "SM_Loadout"
query = { inline = '''
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mud: <https://rocket-craft.com/ontology/mud#>
SELECT ?prim ?part ?type ?translateX ?translateY ?translateZ ?scaleX ?scaleY ?scaleZ ?rotateX ?rotateY ?rotateZ ?materialBinding ?partLocalName ?materialLocalName ?primLocalName
WHERE {
  VALUES (?CURRENT_PART_ID) {
    (mud:backpack_core) (mud:thruster_cluster)
  }
  ?prim rdf:type mud:GeometryPrimitive ;
        mud:belongsToPart ?CURRENT_PART_ID ;
        mud:belongsToPart ?part ;
        mud:primitiveFamily ?type ;
        mud:translateX ?translateX ;
        mud:translateY ?translateY ;
        mud:translateZ ?translateZ ;
        mud:scaleX ?scaleX ;
        mud:scaleY ?scaleY ;
        mud:scaleZ ?scaleZ ;
        mud:rotateX ?rotateX ;
        mud:rotateY ?rotateY ;
        mud:rotateZ ?rotateZ ;
        mud:materialBinding ?materialBinding .
  BIND(STRAFTER(STR(?part), "#") AS ?partLocalName)
  BIND(STRAFTER(STR(?materialBinding), "#") AS ?materialLocalName)
  BIND(STRAFTER(STR(?prim), "#") AS ?primLocalName)
}
ORDER BY ?prim
''' }
mode = "Overwrite"
template = { file = "generated/mech_assets/reference_fabric_001/templates/usd/part_mesh.usda.tera" }
output_file = "generated/mech_assets/reference_fabric_001/usd/SM_Loadout.usda"
"""

if "SM_Limb_Left" not in ggen_content:
    with open("/Users/sac/rocket-craft/ggen.toml", "a") as f:
        f.write(limb_left_rule)
        f.write(limb_right_rule)
        f.write(loadout_rule)
