//! Environment management commands

use clap_noun_verb::Result;
use clap_noun_verb_macros::verb;
use serde_json::Value;

fn do_setup() -> Result<Value> {
    rocket_sdk::setup::run_setup()
        .map_err(|e| clap_noun_verb::NounVerbError::execution_error(format!("{}", e)))?;
    Ok(serde_json::json!({"status": "ok"}))
}

fn do_doctor() -> Result<Value> {
    use rocket_sdk::doctor::{render_diagnostics, RocketDoctor};
    let project_root = std::env::current_dir()
        .map_err(|e| clap_noun_verb::NounVerbError::execution_error(format!("{}", e)))?;

    let doctor = RocketDoctor::new(project_root);
    let report = doctor.run_diagnostics();

    render_diagnostics(&report);

    Ok(serde_json::json!({
        "overall": if report.all_required_pass() { "PASS" } else { "FAIL" },
        "required_pass": report.required_pass_count(),
        "required_total": report.required_total(),
        "timestamp": report.timestamp.to_rfc3339(),
    }))
}

fn do_capabilities() -> Result<Value> {
    let capabilities = [
        (
            "Multiplatform Orchestration",
            "Unified build system for Windows, Linux, Android, and HTML5 (Web).",
        ),
        (
            "Semantic Compliance",
            "Law-based project auditing via the ComplianceEngine and knhk plugin system.",
        ),
        (
            "Generative SDK",
            "Zero-cost typestate kernel in rocket-sdk for safe UE project manipulation.",
        ),
        (
            "PWA Optimization",
            "Automated asset manifest generation and mobile-ready PWA scaffolding.",
        ),
        (
            "Crypto Automation",
            "Automated Android keystore generation and lifecycle management.",
        ),
        (
            "Environment Diagnostics",
            "Rocket Doctor for programmatic workspace health and dependency checks.",
        ),
        (
            "Log Streaming",
            "Real-time colorized log tailing with semantic highlighting for UE4 builds.",
        ),
        (
            "TUI Dashboard",
            "Interactive terminal UI for project management (built with ratatui).",
        ),
        (
            "Wasm Plugin System",
            "Extensible compliance laws via WebAssembly (Wasmer integration).",
        ),
        (
            "Chicago TDD Integration",
            "Automated test orchestration across Rust and Python validation suites.",
        ),
    ];
    let caps_json: Vec<Value> = capabilities
        .iter()
        .map(|(name, desc)| serde_json::json!({"name": name, "description": desc}))
        .collect();
    Ok(serde_json::json!({"capabilities": caps_json}))
}

fn do_config(key: String) -> Result<Value> {
    let config = rocket_sdk::config::RocketConfig::load()
        .map_err(|e| clap_noun_verb::NounVerbError::execution_error(format!("{}", e)))?;
    let val = match key.as_str() {
        "ue4_root" => config.ue4_root.map(|p| p.display().to_string()),
        other => {
            return Err(clap_noun_verb::NounVerbError::execution_error(format!(
                "unknown config key '{}'. Known keys: ue4_root",
                other
            )))
        }
    };
    match val {
        Some(v) => Ok(serde_json::json!({"key": key, "value": v})),
        None => Err(clap_noun_verb::NounVerbError::execution_error(format!(
            "key '{}' is not set in .rocket.json",
            key
        ))),
    }
}

fn do_root() -> Result<Value> {
    let root = std::env::current_dir()
        .map_err(|e| clap_noun_verb::NounVerbError::execution_error(format!("{}", e)))?;
    let mut dir = root.as_path();
    loop {
        if dir.join("project-manifest.json").exists() {
            let path = dir.display().to_string();
            println!("{}", path);
            return Ok(serde_json::json!({"root": path}));
        }
        dir = dir.parent().ok_or_else(|| {
            clap_noun_verb::NounVerbError::execution_error(
                "project-manifest.json not found in any parent directory".to_string(),
            )
        })?;
    }
}

/// Build the content of a .envrc file based on repo structure and current env.
pub fn build_envrc_content(has_versions: bool, has_pwa: bool, has_manifest: bool) -> String {
    let ue4_root = std::env::var("UE4_ROOT").ok();
    let blender_path = std::env::var("BLENDER_PATH").ok();
    let supabase_url = std::env::var("SUPABASE_URL").ok();
    let supabase_anon_key = std::env::var("SUPABASE_ANON_KEY").ok();

    let mut lines: Vec<String> = vec![
        "# rocket-craft .envrc — generated by ./rocket env generate-envrc".to_string(),
        "# Run: direnv allow".to_string(),
        String::new(),
    ];

    if has_versions || has_manifest {
        let ue4_val = ue4_root.as_deref().unwrap_or("/opt/UnrealEngine-4.24");
        lines.push(format!("export UE4_ROOT=\"{ue4_val}\""));
    }

    let blender_val = blender_path
        .as_deref()
        .unwrap_or("/Applications/Blender.app/Contents/MacOS/blender");
    lines.push(format!("export BLENDER_PATH=\"{blender_val}\""));

    if has_pwa {
        let sb_url = supabase_url.as_deref().unwrap_or("http://127.0.0.1:54321");
        let sb_key = supabase_anon_key
            .as_deref()
            .unwrap_or("sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH");
        lines.push(format!("export SUPABASE_URL=\"{sb_url}\""));
        lines.push(format!("export SUPABASE_ANON_KEY=\"{sb_key}\""));
    }

    lines.push("export ROCKET_CLOUD=\"0\"".to_string());
    lines.join("\n") + "\n"
}

fn do_completions(shell: &str) -> Result<Value> {
    use clap_complete::aot::{generate, Shell as ClapShell};
    use clap_noun_verb::cli::CommandRegistry;
    use std::str::FromStr;

    let shell_parsed = ClapShell::from_str(shell).map_err(|_| {
        clap_noun_verb::NounVerbError::execution_error(format!(
            "unsupported shell '{}'. Supported: bash, zsh, fish, elvish, powershell",
            shell
        ))
    })?;
    let registry = CommandRegistry::get();
    let registry = registry
        .lock()
        .map_err(|e| clap_noun_verb::NounVerbError::execution_error(format!("{e}")))?;
    let mut cmd = registry.build_command();
    generate(shell_parsed, &mut cmd, "rocket", &mut std::io::stdout());
    Ok(serde_json::json!({"status": "ok", "shell": shell}))
}

fn do_generate_envrc(force: bool) -> Result<Value> {
    use std::fs;

    let cwd = std::env::current_dir()
        .map_err(|e| clap_noun_verb::NounVerbError::execution_error(format!("{e}")))?;
    let envrc_path = cwd.join(".envrc");

    if envrc_path.exists() && !force {
        return Err(clap_noun_verb::NounVerbError::execution_error(
            ".envrc already exists. Use --force to overwrite.".to_string(),
        ));
    }

    let has_versions = cwd.join("versions").is_dir();
    let has_pwa = cwd.join("pwa-staff").is_dir();
    let has_manifest = cwd.join("project-manifest.json").is_file();

    let content = build_envrc_content(has_versions, has_pwa, has_manifest);
    fs::write(&envrc_path, &content)
        .map_err(|e| clap_noun_verb::NounVerbError::execution_error(format!("{e}")))?;

    println!("{}", content);
    println!("Wrote: {}", envrc_path.display());

    let direnv_installed = std::process::Command::new("direnv")
        .arg("version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);

    if direnv_installed {
        println!("\ndirenv is installed. Run the following to activate:\n\n    direnv allow\n");
    } else {
        println!("\ndirenv is not installed. Install it from https://direnv.net and run:\n\n    direnv allow\n");
    }

    Ok(serde_json::json!({
        "status": "ok",
        "path": envrc_path.display().to_string(),
        "direnv_installed": direnv_installed,
        "has_versions": has_versions,
        "has_pwa": has_pwa,
    }))
}

/// Setup the Unreal Engine environment
#[verb("setup", "env")]
fn setup_env() -> Result<Value> {
    do_setup()
}

/// Troubleshoot the environment
#[verb("doctor", "env")]
fn doctor_env() -> Result<Value> {
    do_doctor()
}

/// Generate shell completions
///
/// # Arguments
/// * `shell` - The shell to generate completions for (bash, zsh, fish)
#[verb("completions", "env")]
fn completions_env(shell: String) -> Result<Value> {
    do_completions(&shell)
}

/// Generate a .envrc file for direnv
///
/// # Arguments
/// * `force` - Overwrite an existing .envrc without prompting
#[verb("generate-envrc", "env")]
fn generate_envrc_env(force: Option<bool>) -> Result<Value> {
    do_generate_envrc(force.unwrap_or(false))
}

/// List all integrated high-level features (Capabilities)
#[verb("capabilities", "env")]
fn capabilities_env() -> Result<Value> {
    do_capabilities()
}

/// Read a value from .rocket.json or project-manifest.json
///
/// # Arguments
/// * `key` - Key to read (e.g. ue4_root)
#[verb("config", "env")]
fn config_env(key: String) -> Result<Value> {
    do_config(key)
}

/// Print the repo root (directory containing project-manifest.json)
#[verb("root", "env")]
fn root_env() -> Result<Value> {
    do_root()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn do_capabilities_returns_10_capabilities() {
        let result = do_capabilities().unwrap();
        let caps = result["capabilities"].as_array().unwrap();
        assert_eq!(caps.len(), 10);
    }

    #[test]
    fn do_capabilities_all_entries_have_name_and_description() {
        let result = do_capabilities().unwrap();
        let caps = result["capabilities"].as_array().unwrap();
        for cap in caps {
            assert!(cap["name"].is_string(), "missing name");
            assert!(cap["description"].is_string(), "missing description");
            assert!(!cap["name"].as_str().unwrap().is_empty(), "empty name");
            assert!(
                !cap["description"].as_str().unwrap().is_empty(),
                "empty description"
            );
        }
    }

    #[test]
    fn do_capabilities_names_are_unique() {
        let result = do_capabilities().unwrap();
        let caps = result["capabilities"].as_array().unwrap();
        let names: Vec<_> = caps.iter().map(|c| c["name"].as_str().unwrap()).collect();
        let unique: std::collections::HashSet<_> = names.iter().collect();
        assert_eq!(names.len(), unique.len(), "duplicate capability name");
    }

    #[test]
    fn do_capabilities_includes_wasm_plugin_system() {
        let result = do_capabilities().unwrap();
        let caps = result["capabilities"].as_array().unwrap();
        assert!(caps.iter().any(|c| c["name"]
            .as_str()
            .unwrap()
            .contains("Wasm Plugin System")));
    }

    #[test]
    fn build_envrc_content_includes_ue4_root_when_versions_present() {
        let content = build_envrc_content(true, false, false);
        assert!(content.contains("UE4_ROOT="));
    }

    #[test]
    fn build_envrc_content_includes_ue4_root_when_manifest_present() {
        let content = build_envrc_content(false, false, true);
        assert!(content.contains("UE4_ROOT="));
    }

    #[test]
    fn build_envrc_content_omits_ue4_root_when_neither_present() {
        let content = build_envrc_content(false, false, false);
        assert!(!content.contains("UE4_ROOT="));
    }

    #[test]
    fn build_envrc_content_includes_supabase_when_pwa_present() {
        let content = build_envrc_content(false, true, false);
        assert!(content.contains("SUPABASE_URL="));
        assert!(content.contains("SUPABASE_ANON_KEY="));
    }

    #[test]
    fn build_envrc_content_omits_supabase_when_no_pwa() {
        let content = build_envrc_content(false, false, false);
        assert!(!content.contains("SUPABASE_URL="));
    }

    #[test]
    fn build_envrc_content_always_includes_blender_and_rocket_cloud() {
        let content = build_envrc_content(false, false, false);
        assert!(content.contains("BLENDER_PATH="));
        assert!(content.contains("ROCKET_CLOUD="));
    }

    #[test]
    fn build_envrc_content_starts_with_header_comment() {
        let content = build_envrc_content(false, false, false);
        assert!(content.starts_with("# rocket-craft .envrc"));
    }
}
