use crate::diagnostics::AntiLlmDiagnostic;
use crate::observations::Observation;

pub fn evaluate(obs: &[Observation]) -> Vec<AntiLlmDiagnostic> {
    let mut diags = Vec::new();

    for o in obs {
        // Check for test result treated as receipt
        if o.construct == "test result: ok" {
            diags.push(AntiLlmDiagnostic {
                code: "ANTI-LLM-RECEIPT-001".to_string(),
                category: "receipt".to_string(),
                file_path: o.file_path.clone(),
                line: o.line,
                column: o.column,
                message: "Test stdout treated as receipt. Test output is not a cryptographically signed receipt.".to_string(),
                forbidden_implication: "TestStdout => Receipt".to_string(),
                blocking: true,
                required_correction: "Write process evidence into a BLAKE3/SHA-256 JSON receipt file instead of asserting on stdout.".to_string(),
                required_next_proof: "Verify receipt exists on disk with a valid BLAKE3 hash.".to_string(),
            });
        }

        // Check for log message treated as receipt
        if o.construct == "LogMessage => Receipt" || o.message.contains("LogMessage => Receipt") {
            diags.push(AntiLlmDiagnostic {
                code: "ANTI-LLM-RECEIPT-002".to_string(),
                category: "receipt".to_string(),
                file_path: o.file_path.clone(),
                line: o.line,
                column: o.column,
                message: "Log message treated as receipt. Logging is not admission/process evidence.".to_string(),
                forbidden_implication: "LogMessage => Receipt".to_string(),
                blocking: true,
                required_correction: "Produce a proper json receipt for actions instead of logging them.".to_string(),
                required_next_proof: "Verify receipt is generated by the MutationGate.".to_string(),
            });
        }

        // Check for missing receipt path
        if o.message.contains("Receipt file lacks required field")
            || o.construct == "missing digest"
        {
            diags.push(AntiLlmDiagnostic {
                code: "ANTI-LLM-RECEIPT-003".to_string(),
                category: "receipt".to_string(),
                file_path: o.file_path.clone(),
                line: o.line,
                column: o.column,
                message: "Receipt path or required field is missing.".to_string(),
                forbidden_implication: "Claimed proof => receipt exists".to_string(),
                blocking: true,
                required_correction:
                    "Make sure receipt file exists and conforms to receipt schema.".to_string(),
                required_next_proof:
                    "Verify receipt fields (digest, raw_command, boundary) are complete."
                        .to_string(),
            });
        }
    }

    diags
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::observations::Observation;

    fn obs(construct: &str, message: &str) -> Observation {
        Observation {
            file_path: "src/lib.rs".into(), line: 1, column: 0,
            start_byte: 0, end_byte: 0,
            kind: "receipt_smell".into(),
            construct: construct.into(), context: String::new(), message: message.into(),
        }
    }

    #[test]
    fn empty_returns_no_diags() {
        assert!(evaluate(&[]).is_empty());
    }

    #[test]
    fn test_result_ok_triggers_receipt_001() {
        let diags = evaluate(&[obs("test result: ok", "")]);
        assert_eq!(diags[0].code, "ANTI-LLM-RECEIPT-001");
        assert!(diags[0].blocking);
    }

    #[test]
    fn log_message_construct_triggers_receipt_002() {
        let diags = evaluate(&[obs("LogMessage => Receipt", "")]);
        assert_eq!(diags[0].code, "ANTI-LLM-RECEIPT-002");
        assert!(diags[0].blocking);
    }

    #[test]
    fn log_message_in_message_field_triggers_receipt_002() {
        let diags = evaluate(&[obs("anything", "LogMessage => Receipt")]);
        assert_eq!(diags[0].code, "ANTI-LLM-RECEIPT-002");
    }

    #[test]
    fn missing_digest_triggers_receipt_003() {
        let diags = evaluate(&[obs("missing digest", "")]);
        assert_eq!(diags[0].code, "ANTI-LLM-RECEIPT-003");
        assert!(diags[0].blocking);
    }

    #[test]
    fn message_contains_lacks_required_field_triggers_receipt_003() {
        let diags = evaluate(&[obs("anything", "Receipt file lacks required field 'digest'")]);
        assert_eq!(diags[0].code, "ANTI-LLM-RECEIPT-003");
    }

    #[test]
    fn unknown_construct_produces_no_diag() {
        let diags = evaluate(&[obs("normal_thing", "all good")]);
        assert!(diags.is_empty());
    }
}
