SELECT ?class ?label ?comment
WHERE {
  ?class <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .
  OPTIONAL { ?class <http://www.w3.org/2000/01/rdf-schema#label> ?label }
  OPTIONAL { ?class <http://www.w3.org/2000/01/rdf-schema#comment> ?comment }
}
ORDER BY ?class
