//! T3D serializer — converts a Blueprint AST to UE4 T3D copy/paste format.
//!
//! The output can be pasted directly into the UE4 Blueprint editor Event Graph
//! (Ctrl+V) and the nodes will appear with their connections intact.

use crate::ast::{Blueprint, BpGraph, BpNode, Pin};
use crate::types::{PinDirection, PinCategory};

pub struct T3dSerializer;

impl T3dSerializer {
    /// Serialize a single [`BpGraph`] to a flat sequence of `Begin Object … End Object` blocks.
    ///
    /// Unlike [`Self::serialize`], this does **not** wrap the output in a `K2Node_Tunnel`
    /// container, so it matches the format expected by [`crate::parser::parse_t3d`].
    pub fn serialize_graph(graph: &BpGraph) -> String {
        let mut out = String::new();
        for node in &graph.nodes {
            out.push_str(&serialize_node(node));
            out.push('\n');
        }
        out
    }

    /// Serialize a `Blueprint` to UE4 T3D format string.
    pub fn serialize(bp: &Blueprint) -> String {
        let mut out = String::new();

        out.push_str("Begin Object Class=/Script/BlueprintGraph.K2Node_Tunnel Name=\"Graph\"\n");

        for graph in &bp.graphs {
            out.push_str(&format!("   // Graph: {}\n", graph.name));
            for node in &graph.nodes {
                out.push_str(&serialize_node(node));
                out.push('\n');
            }
        }

        out.push_str("End Object\n");
        out
    }

    /// Serialize with a header comment explaining the source.
    pub fn serialize_with_header(bp: &Blueprint) -> String {
        let mut out = format!(
            "// Generated by blueprint-rs — Blueprint: {}, Parent: {}\n",
            bp.name, bp.parent_class
        );
        out.push_str(&Self::serialize(bp));
        out
    }
}

fn serialize_node(node: &BpNode) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "Begin Object Class={} Name=\"{}\"\n",
        node.class, node.name
    ));

    // Node position
    out.push_str(&format!(
        "   NodePosX={}\n   NodePosY={}\n",
        node.pos.x, node.pos.y
    ));

    // Node GUID
    out.push_str(&format!("   NodeGuid={}\n", node.id));

    // Extra properties (e.g. EventReference, FunctionReference)
    // Sort for deterministic output
    let mut props: Vec<(&String, &String)> = node.properties.iter().collect();
    props.sort_by_key(|(k, _)| k.as_str());
    for (k, v) in &props {
        out.push_str(&format!("   {}={}\n", k, v));
    }

    // Pins
    for (i, pin) in node.pins.iter().enumerate() {
        out.push_str(&serialize_pin(pin, i));
    }

    out.push_str("End Object\n");
    out
}

fn serialize_pin(pin: &Pin, _index: usize) -> String {
    let mut parts = Vec::new();

    parts.push(format!("PinId={}", pin.id));
    parts.push(format!("PinName=\"{}\"", pin.name));

    if let Some(dn) = &pin.display_name {
        parts.push(format!("PinFriendlyName=\"{}\"", dn));
    }

    // Direction
    let dir_str = match pin.direction {
        PinDirection::Input => "EGPD_Input",
        PinDirection::Output => "EGPD_Output",
    };
    parts.push(format!("Direction=\"{}\"", dir_str));

    // PinType — PinCategory
    parts.push(format!("PinType.PinCategory=\"{}\"", pin.pin_type.category.as_str()));

    if let Some(sub) = &pin.pin_type.sub_category {
        parts.push(format!("PinType.PinSubCategory=\"{}\"", sub));
    }

    if let Some(obj) = &pin.pin_type.sub_category_object {
        parts.push(format!("PinType.PinSubCategoryObject={}", obj));
    }

    // LinkedTo list
    for link in &pin.linked_to {
        parts.push(format!(
            "LinkedTo=({}({}))",
            link.node_name, link.pin_id
        ));
    }

    // Default value (skip for exec pins)
    if pin.pin_type.category != PinCategory::Exec {
        if let Some(dv) = &pin.default_value {
            parts.push(format!("DefaultValue=\"{}\"", dv));
        }
    }

    if pin.is_hidden {
        parts.push("bHidden=True".to_string());
    }
    if pin.is_not_connectable {
        parts.push("bNotConnectable=True".to_string());
    }
    if pin.is_advanced_view {
        parts.push("bAdvancedView=True".to_string());
    }
    if pin.is_orphaned {
        parts.push("bOrphanedPin=True".to_string());
    }

    format!(
        "   CustomProperties Pin ({})\n",
        parts.join(",")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::BpNode;
    use crate::types::{PinDirection, PinType, PinCategory, ContainerType};

    fn make_event_node() -> BpNode {
        BpNode::new(
            "/Script/BlueprintGraph.K2Node_Event",
            "K2Node_Event_0",
        )
        .at(64, -16)
        .with_property(
            "EventReference",
            "(MemberParent=Class'/Script/Engine.Actor',MemberName=\"ReceiveBeginPlay\")",
        )
        .with_property("bOverrideFunction", "True")
        .with_pin({
            let mut p = Pin::new(
                "OutputDelegate",
                PinDirection::Output,
                PinType {
                    category: PinCategory::Delegate,
                    sub_category: None,
                    sub_category_object: None,
                    container: ContainerType::None,
                    is_reference: false,
                    is_const: false,
                },
            );
            p.is_hidden = true;
            p.is_not_connectable = true;
            p
        })
        .with_pin(Pin::exec_output("then"))
    }

    #[test]
    fn test_event_node_structure() {
        let node = make_event_node();
        let t3d = serialize_node(&node);

        assert!(t3d.contains("Begin Object"), "missing Begin Object:\n{}", t3d);
        assert!(t3d.contains("K2Node_Event_0"), "missing node name:\n{}", t3d);
        assert!(t3d.contains("NodeGuid="), "missing NodeGuid:\n{}", t3d);
        assert!(t3d.contains("End Object"), "missing End Object:\n{}", t3d);
        assert!(
            t3d.contains("/Script/BlueprintGraph.K2Node_Event"),
            "missing class:\n{}",
            t3d
        );
        assert!(t3d.contains("NodePosX=64"), "missing NodePosX:\n{}", t3d);
        assert!(t3d.contains("NodePosY=-16"), "missing NodePosY:\n{}", t3d);
        assert!(
            t3d.contains("CustomProperties Pin"),
            "missing pin:\n{}",
            t3d
        );
        // Output pins include Direction field
        assert!(
            t3d.contains("Direction=\"EGPD_Output\""),
            "missing Direction on output pin:\n{}",
            t3d
        );
    }

    #[test]
    fn test_connected_exec_pin_produces_linked_to() {
        // Build a graph with two nodes connected by exec pins
        let mut graph = BpGraph::new("TestGraph");

        let event_node = BpNode::new(
            "/Script/BlueprintGraph.K2Node_Event",
            "K2Node_Event_0",
        )
        .at(64, -16)
        .with_pin(Pin::exec_output("then"));

        let call_node = BpNode::new(
            "/Script/BlueprintGraph.K2Node_CallFunction",
            "K2Node_CallFunction_0",
        )
        .at(320, -16)
        .with_pin(Pin::exec_input("execute"))
        .with_pin(Pin::exec_output("then"));

        graph.add_node(event_node);
        graph.add_node(call_node);

        // Wire K2Node_Event_0:then -> K2Node_CallFunction_0:execute
        graph.connect("K2Node_Event_0", "then", "K2Node_CallFunction_0", "execute");

        let t3d = T3dSerializer::serialize_graph(&graph);

        assert!(
            t3d.contains("LinkedTo="),
            "expected LinkedTo in output, got:\n{}",
            t3d
        );
        assert!(
            t3d.contains("K2Node_CallFunction_0"),
            "expected target node name in LinkedTo, got:\n{}",
            t3d
        );
        assert!(
            t3d.contains("K2Node_Event_0"),
            "expected source node name in LinkedTo, got:\n{}",
            t3d
        );
    }

    #[test]
    fn test_input_pin_has_direction_attribute() {
        let node = BpNode::new(
            "/Script/BlueprintGraph.K2Node_CallFunction",
            "K2Node_CallFunction_0",
        )
        .with_pin(Pin::exec_input("execute"));

        let t3d = serialize_node(&node);

        // The "execute" pin is an input pin and has Direction="EGPD_Input" in its CustomProperties
        let exec_pin_line = t3d
            .lines()
            .find(|l| l.contains("PinName=\"execute\""))
            .unwrap_or("");
        assert!(
            exec_pin_line.contains("Direction=\"EGPD_Input\""),
            "input pin must have EGPD_Input direction attribute, got: {}",
            exec_pin_line
        );
    }

    #[test]
    fn test_default_value_serialized() {
        let mut pin = Pin::data_input("InString", PinType::string());
        pin.default_value = Some("Hello!".to_string());

        let node = BpNode::new(
            "/Script/BlueprintGraph.K2Node_CallFunction",
            "K2Node_CallFunction_0",
        )
        .with_pin(pin);

        let t3d = serialize_node(&node);
        assert!(
            t3d.contains("DefaultValue=\"Hello!\""),
            "missing DefaultValue in output:\n{}",
            t3d
        );
    }

    #[test]
    fn test_serialize_with_header() {
        let bp = Blueprint::new("MyBlueprint", "Actor");
        let t3d = T3dSerializer::serialize_with_header(&bp);
        assert!(
            t3d.starts_with("// Generated by blueprint-rs"),
            "missing header comment:\n{}",
            t3d
        );
        assert!(
            t3d.contains("MyBlueprint"),
            "missing blueprint name in header:\n{}",
            t3d
        );
        assert!(
            t3d.contains("Actor"),
            "missing parent class in header:\n{}",
            t3d
        );
    }

    #[test]
    fn test_multiple_graphs_have_comments() {
        let mut bp = Blueprint::new("MyBlueprint", "Actor");
        // Blueprint::new adds EventGraph automatically; add a second one
        bp.function_graph("MyFunction");

        let t3d = T3dSerializer::serialize(&bp);
        assert!(
            t3d.contains("// Graph: EventGraph") || t3d.contains("// Graph: MyFunction"),
            "missing graph comment:\n{}",
            t3d
        );
    }
}
