// Generated by rocket-preue4-verifier — GC-GUNDAM-FACTORY-001
// Source: GundamFactory.powl — POWL_GRAMMAR_TRACE_ALIVE_UNDER_SCOPE
// Do NOT edit manually.
#pragma once

enum class EGundamFactoryStep : uint8 {
    Spawn = 0,
    FactoryEntrance = 1,
    FrameAssembly = 2,
    SocketTopology = 3,
    ArmorSkinStation = 4,
    SubframeAssemblyStation = 5,
    FeatherBladeStation = 6,
    RigMotionStation = 7,
    VerificationGate = 8,
    ReceiptTerminal = 9,
    ExitOrLoop = 10,
    COUNT = 11
};
