use crate::store::TripleStore;
use crate::triple::{Term, Triple};

/// Configuration for the ontology pipeline.
#[derive(Debug, Default, Clone, serde::Serialize, serde::Deserialize)]
pub struct PipelineConfig {
    /// Target language: "rust", "go", "typescript", "elixir", "python", etc.
    pub target_language: String,
    /// Output directory for generated files.
    pub output_dir: String,
    /// Optional custom template directory.
    pub template_dir: Option<String>,
    /// Base namespace IRI.
    pub namespace: String,
}

/// A single generated file produced by the pipeline.
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
    /// Kind discriminator, e.g. "struct", "interface", "module".
    pub kind: String,
}

/// The output of a completed pipeline run.
pub struct PipelineOutput {
    pub files: Vec<GeneratedFile>,
    /// BLAKE3 hash of all output file contents concatenated.
    pub receipt: String,
}

/// Mirrors ggen's 5-stage μ₁–μ₅ pipeline:
///   μ₁ ontology load → μ₂ SPARQL extraction → μ₃ template rendering
///   → μ₄ canonicalization → μ₅ receipt
pub struct OntologyPipeline {
    store: TripleStore,
    config: PipelineConfig,
}

impl OntologyPipeline {
    pub fn new(store: TripleStore, config: PipelineConfig) -> Self {
        OntologyPipeline { store, config }
    }

    /// μ₁: Load RDF/Turtle content.
    /// This is a minimal stub: blank lines and comment lines are skipped;
    /// each remaining line is parsed as a simple N-Triples-style triple.
    /// Returns the number of triples added.
    pub fn load_turtle(&mut self, turtle: &str) -> Result<usize, String> {
        let before = self.store.len();
        for line in turtle.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            // Accept simple "subject predicate object ." lines
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 3 {
                let s = parts[0].trim_matches(|c| c == '<' || c == '>');
                let p = parts[1].trim_matches(|c| c == '<' || c == '>');
                let o = parts[2].trim_matches(|c| c == '<' || c == '>' || c == '.');
                self.store.add(Triple::new(s, p, o));
            }
        }
        Ok(self.store.len() - before)
    }

    /// μ₂: Extract rdf:type subjects from the store.
    pub fn extract_types(&self) -> Vec<String> {
        let rdf_type = Term::Named("rdf:type".into());
        self.store
            .query_predicate(&rdf_type)
            .into_iter()
            .map(|t| match &t.subject {
                Term::Named(iri) => iri.clone(),
                Term::Blank(id) => format!("_:{}", id),
                Term::Literal { value, .. } => value.clone(),
            })
            .collect()
    }

    /// μ₃–μ₅: Stub rendering, canonicalization, and receipt generation.
    pub fn render(&self) -> Result<PipelineOutput, String> {
        let types = self.extract_types();
        let mut files = Vec::new();
        for ty in &types {
            let type_name = ty.split('/').last().unwrap_or(ty);
            let (ext, content) = match self.config.target_language.as_str() {
                "rust" => (
                    "rs",
                    format!(
                        "// Generated by unify-rdf\npub struct {} {{}}\n",
                        type_name
                    ),
                ),
                "go" => (
                    "go",
                    format!(
                        "// Generated by unify-rdf\npackage {}\ntype {} struct {{}}\n",
                        self.config.namespace, type_name
                    ),
                ),
                "typescript" => (
                    "ts",
                    format!(
                        "// Generated by unify-rdf\nexport interface {} {{}}\n",
                        type_name
                    ),
                ),
                _ => (
                    "txt",
                    format!("// Generated by unify-rdf\n// Type: {}\n", type_name),
                ),
            };
            files.push(GeneratedFile {
                path: format!("{}/{}.{}", self.config.output_dir, type_name, ext),
                content,
                kind: "type".into(),
            });
        }
        // μ₄ canonicalization: sort by path for determinism
        files.sort_by(|a, b| a.path.cmp(&b.path));
        // μ₅ receipt: hash of all content
        let combined: String = files.iter().map(|f| f.content.as_str()).collect();
        let receipt = blake3::hash(combined.as_bytes()).to_hex().to_string();
        Ok(PipelineOutput { files, receipt })
    }

    /// Always 5 stages (μ₁–μ₅).
    pub fn stage_count(&self) -> usize {
        5
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    fn default_config() -> PipelineConfig {
        PipelineConfig {
            target_language: "rust".into(),
            output_dir: "out".into(),
            template_dir: None,
            namespace: "example".into(),
        }
    }

    #[test]
    fn test_pipeline_new_and_stage_count() {
        let pipeline = OntologyPipeline::new(TripleStore::new(), default_config());
        assert_eq!(pipeline.stage_count(), 5);
    }

    #[test]
    fn test_pipeline_load_turtle_increases_triple_count() {
        let mut pipeline = OntologyPipeline::new(TripleStore::new(), default_config());
        let turtle = "<http://example.org/Foo> rdf:type <http://schema.org/Thing> .\n\
                      <http://example.org/Bar> rdf:type <http://schema.org/Thing> .";
        let added = pipeline.load_turtle(turtle).unwrap();
        assert_eq!(added, 2);
        assert_eq!(pipeline.store.len(), 2);
    }

    #[test]
    fn test_pipeline_extract_types_returns_rdf_type_subjects() {
        let mut pipeline = OntologyPipeline::new(TripleStore::new(), default_config());
        let turtle = "<http://example.org/Foo> rdf:type <http://schema.org/Thing> .";
        pipeline.load_turtle(turtle).unwrap();
        let types = pipeline.extract_types();
        assert_eq!(types.len(), 1);
        assert!(types[0].contains("Foo"));
    }

    #[test]
    fn test_pipeline_render_produces_output() {
        let mut pipeline = OntologyPipeline::new(TripleStore::new(), default_config());
        pipeline.load_turtle("<http://example.org/MyType> rdf:type <http://schema.org/Thing> .").unwrap();
        let output = pipeline.render().unwrap();
        assert_eq!(output.files.len(), 1);
        assert!(!output.receipt.is_empty());
        assert!(output.files[0].content.contains("MyType"));
    }
}
