use anyhow::Result;
use blake3::Hasher;
use serde::{Deserialize, Serialize};

pub mod telemetry;

use std::path::{Path, PathBuf};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct RocketContract {
    pub name: String,
    pub world_seed: u64,
    pub es3_enabled: bool,
    pub target_platform: String,
    pub features: Vec<String>,
}

impl RocketContract {
    pub fn new(name: String, world_seed: u64) -> Self {
        Self {
            name,
            world_seed,
            es3_enabled: true,
            target_platform: "HTML5".to_string(),
            features: vec!["WASM".to_string(), "WebGL2".to_string()],
        }
    }

    pub fn compute_hash(&self) -> String {
        let mut hasher = Hasher::new();
        hasher.update(self.name.as_bytes());
        hasher.update(&self.world_seed.to_le_bytes());
        hasher.update(&[self.es3_enabled as u8]);
        hasher.update(self.target_platform.as_bytes());
        for feature in &self.features {
            hasher.update(feature.as_bytes());
        }
        hasher.finalize().to_hex().to_string()
    }

    pub fn generate_artifact(&self, output_dir: &Path) -> Result<PathBuf> {
        let hash = self.compute_hash();
        let artifact_name = format!("{}_{}.json", self.name, hash);
        let artifact_path = output_dir.join(artifact_name);

        let content = serde_json::to_string_pretty(self)?;
        std::fs::write(&artifact_path, content)?;

        Ok(artifact_path)
    }
}

pub struct SimulationEngine {
    pub contract: RocketContract,
    pub workspace_root: PathBuf,
}

impl SimulationEngine {
    pub fn new(contract: RocketContract, workspace_root: PathBuf) -> Self {
        Self {
            contract,
            workspace_root,
        }
    }

    pub fn prepare_manufacturing(&self) -> Result<()> {
        let artifact_dir = self.workspace_root.join(".ggen").join("artifacts");
        std::fs::create_dir_all(&artifact_dir)?;

        let artifact_path = self.contract.generate_artifact(&artifact_dir)?;
        tracing::info!("Generated UE4 world artifact: {}", artifact_path.display());

        Ok(())
    }

    pub fn run_e2e_simulation(&self) -> Result<Receipt> {
        // 1. Kill any existing server on port 3000
        let _ = std::process::Command::new("sh")
            .arg("-c")
            .arg("lsof -t -i:3000 | xargs kill -9")
            .status();

        // 2. Start the local node server
        let server_script = self.workspace_root.join("genie_server.js");
        if !server_script.exists() {
            return Err(anyhow::anyhow!(
                "genie_server.js not found at {}",
                server_script.display()
            ));
        }

        let mut server_child = std::process::Command::new("node")
            .arg(&server_script)
            .current_dir(&self.workspace_root)
            .spawn()?;

        // 3. Wait for the server to spin up
        std::thread::sleep(std::time::Duration::from_secs(3));

        // 4. Spawn the Playwright E2E test
        let pwa_dir = self.workspace_root.join("pwa-staff");
        let mut playwright_cmd = std::process::Command::new("npx");
        playwright_cmd
            .args(["playwright", "test", "tests-e2e/tps-dflss.spec.ts"])
            .current_dir(&pwa_dir);

        let status = playwright_cmd.status();

        // Ensure we kill the server child when returning
        let _ = server_child.kill();

        let status = status?;
        if !status.success() {
            return Err(anyhow::anyhow!("Playwright E2E test execution failed"));
        }

        // 5. Parse and verify receipt
        let receipt_path = pwa_dir.join("test-results/tps-dflss-receipt.json");
        if !receipt_path.exists() {
            return Err(anyhow::anyhow!(
                "Receipt file was not generated by Playwright"
            ));
        }

        let verified = verify_receipt_signature(&receipt_path)?;
        if !verified {
            return Err(anyhow::anyhow!(
                "Cryptographic signature verification failed for receipt"
            ));
        }

        let content = std::fs::read_to_string(&receipt_path)?;
        let receipt: Receipt = serde_json::from_str(&content)?;

        if receipt.verdict != "PASS" {
            return Err(anyhow::anyhow!("E2E test verdict was not PASS"));
        }

        Ok(receipt)
    }
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Screenshots {
    pub before: String,
    pub after: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Receipt {
    pub timestamp: String,
    pub prompt: String,
    pub contract_hash: String,
    pub build_log: String,
    pub package_path: String,
    pub browser_url: String,
    pub screenshots: Screenshots,
    pub console_logs: Vec<String>,
    pub input_trace: Vec<String>,
    pub visual_delta: u64,
    pub verdict: String,
    pub signature: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct UnsignedReceipt {
    pub timestamp: String,
    pub prompt: String,
    pub contract_hash: String,
    pub build_log: String,
    pub package_path: String,
    pub browser_url: String,
    pub screenshots: Screenshots,
    pub console_logs: Vec<String>,
    pub input_trace: Vec<String>,
    pub visual_delta: u64,
    pub verdict: String,
}

pub fn verify_receipt_signature(path: &Path) -> Result<bool> {
    let content = std::fs::read_to_string(path)?;
    let receipt: Receipt = serde_json::from_str(&content)?;
    let signature = match &receipt.signature {
        Some(sig) => sig,
        None => return Ok(false),
    };

    // Method 1: Re-serialization
    let unsigned = UnsignedReceipt {
        timestamp: receipt.timestamp.clone(),
        prompt: receipt.prompt.clone(),
        contract_hash: receipt.contract_hash.clone(),
        build_log: receipt.build_log.clone(),
        package_path: receipt.package_path.clone(),
        browser_url: receipt.browser_url.clone(),
        screenshots: receipt.screenshots.clone(),
        console_logs: receipt.console_logs.clone(),
        input_trace: receipt.input_trace.clone(),
        visual_delta: receipt.visual_delta,
        verdict: receipt.verdict.clone(),
    };

    let serialized = serde_json::to_string_pretty(&unsigned)?;

    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(serialized.as_bytes());
    let computed_sig = format!("{:x}", hasher.finalize());

    if computed_sig == *signature {
        return Ok(true);
    }

    // Method 2: Manual string reconstruction (LF)
    if let Some(sig_pos) = content.rfind("\"signature\"") {
        if let Some(comma_pos) = content[..sig_pos].rfind(',') {
            let prefix = &content[..comma_pos];

            // Try LF
            let reconstructed_lf = format!("{}\n}}", prefix);
            let mut hasher_lf = Sha256::new();
            hasher_lf.update(reconstructed_lf.as_bytes());
            let computed_sig_lf = format!("{:x}", hasher_lf.finalize());
            if computed_sig_lf == *signature {
                return Ok(true);
            }

            // Try CRLF
            let reconstructed_crlf = format!("{}\r\n}}", prefix);
            let mut hasher_crlf = Sha256::new();
            hasher_crlf.update(reconstructed_crlf.as_bytes());
            let computed_sig_crlf = format!("{:x}", hasher_crlf.finalize());
            if computed_sig_crlf == *signature {
                return Ok(true);
            }
        }
    }

    Ok(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_rocket_contract_hash() {
        let contract = RocketContract::new("test_rocket".to_string(), 42);
        let hash = contract.compute_hash();
        assert!(!hash.is_empty());
    }

    #[test]
    fn test_generate_artifact() {
        let dir = tempdir().unwrap();
        let contract = RocketContract::new("test_artifact".to_string(), 123);
        let path = contract.generate_artifact(dir.path()).unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(path).unwrap();
        let loaded: RocketContract = serde_json::from_str(&content).unwrap();
        assert_eq!(loaded.name, contract.name);
        assert_eq!(loaded.world_seed, contract.world_seed);
    }

    #[test]
    fn test_verify_receipt_signature_existing() {
        let path =
            Path::new("/Users/sac/rocket-craft/pwa-staff/test-results/tps-dflss-receipt.json");
        if path.exists() {
            let verified = verify_receipt_signature(path).unwrap();
            assert!(
                verified,
                "Signature verification failed for existing receipt!"
            );
        }
    }
}

    #[test]
    fn rocket_contract_new_sets_defaults() {
        let c = RocketContract::new("my-rocket".to_string(), 99);
        assert_eq!(c.name, "my-rocket");
        assert_eq!(c.world_seed, 99);
        assert!(c.es3_enabled);
        assert_eq!(c.target_platform, "HTML5");
        assert!(c.features.contains(&"WASM".to_string()));
        assert!(c.features.contains(&"WebGL2".to_string()));
    }

    #[test]
    fn rocket_contract_hash_is_deterministic() {
        let c1 = RocketContract::new("r".to_string(), 1);
        let c2 = RocketContract::new("r".to_string(), 1);
        assert_eq!(c1.compute_hash(), c2.compute_hash());
    }

    #[test]
    fn rocket_contract_different_seeds_different_hashes() {
        let c1 = RocketContract::new("r".to_string(), 1);
        let c2 = RocketContract::new("r".to_string(), 2);
        assert_ne!(c1.compute_hash(), c2.compute_hash());
    }

    #[test]
    fn rocket_contract_hash_is_64_hex_chars() {
        let c = RocketContract::new("x".to_string(), 0);
        // BLAKE3 output hex-encoded = 64 chars
        assert_eq!(c.compute_hash().len(), 64);
    }
