// Generated by ggen. DO NOT EDIT.
#![allow(unused_imports, dead_code)]

use std::marker::PhantomData;




// Zero-sized state markers


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Attacking;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Dodging;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Idle;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Parrying;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PerfectParrying;






















/// Typestate combat state machine kernel
#[derive(Debug, Clone)]
pub struct Machine<L, P> {
    pub _law: std::marker::PhantomData<L>,
    pub hp: f32,
    pub max_hp: f32,
    pub combo_depth: u32,
    pub phase: P,
}

pub trait CombatMachineLaw {
    fn begin_attack(hp: f32, max_hp: f32, combo_depth: u32, dir: crate::parry::AttackDir) -> Result<(f32, f32, u32, crate::parry::AttackDir), anyhow::Error>;
    fn begin_parry(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error>;
    fn begin_perfect_parry(hp: f32, max_hp: f32, combo_depth: u32, dir: crate::parry::AttackDir) -> Result<(f32, f32, u32, crate::parry::AttackDir), anyhow::Error>;
    fn begin_dodge(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error>;
    fn resolve_hit(hp: f32, max_hp: f32, combo_depth: u32, damage: f32, target_hp: &mut f32) -> Result<(f32, f32, u32), anyhow::Error>;
    fn resolve_blocked(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error>;
    fn resolve_parry(hp: f32, max_hp: f32, combo_depth: u32, outcome: crate::parry::ParryOutcome, incoming_damage: f32) -> Result<(f32, f32, u32, crate::parry::ParryOutcome), anyhow::Error>;
    fn resolve_perfect_parry(hp: f32, max_hp: f32, combo_depth: u32, announced: crate::parry::AttackDir, player_dir: crate::parry::AttackDir, incoming_damage: f32) -> Result<(f32, f32, u32, crate::parry::ParryOutcome), anyhow::Error>;
    fn resolve_dodge(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error>;
}

impl<L: CombatMachineLaw> Machine<L, Idle> {
    pub fn new(hp: f32) -> Self {
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp: hp,
            combo_depth: 0,
            phase: Idle,
        }
    }

    pub fn begin_attack(self, dir: crate::parry::AttackDir) -> (Machine<L, Attacking>, crate::parry::AttackDir) {
        let (hp, max_hp, combo_depth, out_dir) = L::begin_attack(self.hp, self.max_hp, self.combo_depth, dir).unwrap();
        (
            Machine {
                _law: std::marker::PhantomData,
                hp,
                max_hp,
                combo_depth,
                phase: Attacking,
            },
            out_dir,
        )
    }

    pub fn begin_parry(self) -> Machine<L, Parrying> {
        let (hp, max_hp, combo_depth) = L::begin_parry(self.hp, self.max_hp, self.combo_depth).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Parrying,
        }
    }

    pub fn begin_perfect_parry(self, dir: crate::parry::AttackDir) -> (Machine<L, PerfectParrying>, crate::parry::AttackDir) {
        let (hp, max_hp, combo_depth, out_dir) = L::begin_perfect_parry(self.hp, self.max_hp, self.combo_depth, dir).unwrap();
        (
            Machine {
                _law: std::marker::PhantomData,
                hp,
                max_hp,
                combo_depth,
                phase: PerfectParrying,
            },
            out_dir,
        )
    }

    pub fn begin_dodge(self) -> Machine<L, Dodging> {
        let (hp, max_hp, combo_depth) = L::begin_dodge(self.hp, self.max_hp, self.combo_depth).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Dodging,
        }
    }
}

impl<L: CombatMachineLaw> Machine<L, Attacking> {
    pub fn resolve_hit(self, damage: f32, target_hp: &mut f32) -> Machine<L, Idle> {
        let (hp, max_hp, combo_depth) = L::resolve_hit(self.hp, self.max_hp, self.combo_depth, damage, target_hp).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Idle,
        }
    }

    pub fn resolve_blocked(self) -> Machine<L, Idle> {
        let (hp, max_hp, combo_depth) = L::resolve_blocked(self.hp, self.max_hp, self.combo_depth).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Idle,
        }
    }
}

impl<L: CombatMachineLaw> Machine<L, Parrying> {
    pub fn resolve(self, outcome: crate::parry::ParryOutcome, incoming_damage: f32) -> (Machine<L, Idle>, crate::parry::ParryOutcome) {
        let (hp, max_hp, combo_depth, out_outcome) = L::resolve_parry(self.hp, self.max_hp, self.combo_depth, outcome, incoming_damage).unwrap();
        (
            Machine {
                _law: std::marker::PhantomData,
                hp,
                max_hp,
                combo_depth,
                phase: Idle,
            },
            out_outcome,
        )
    }
}

impl<L: CombatMachineLaw> Machine<L, PerfectParrying> {
    pub fn resolve(
        self,
        announced: crate::parry::AttackDir,
        player_dir: crate::parry::AttackDir,
        incoming_damage: f32,
    ) -> (Machine<L, Idle>, crate::parry::ParryOutcome) {
        let (hp, max_hp, combo_depth, outcome) = L::resolve_perfect_parry(self.hp, self.max_hp, self.combo_depth, announced, player_dir, incoming_damage).unwrap();
        (
            Machine {
                _law: std::marker::PhantomData,
                hp,
                max_hp,
                combo_depth,
                phase: Idle,
            },
            outcome,
        )
    }
}

impl<L: CombatMachineLaw> Machine<L, Dodging> {
    pub fn resolve(self) -> Machine<L, Idle> {
        let (hp, max_hp, combo_depth) = L::resolve_dodge(self.hp, self.max_hp, self.combo_depth).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Idle,
        }
    }
}


#[cfg(test)]
mod tests {
    use super::*;
    use crate::parry::{AttackDir, ParryOutcome};

    // A passthrough Law implementation for testing — delegates to direct math
    pub struct DefaultLaw;

    impl CombatMachineLaw for DefaultLaw {
        fn begin_attack(hp: f32, max_hp: f32, combo_depth: u32, dir: AttackDir) -> Result<(f32, f32, u32, AttackDir), anyhow::Error> {
            Ok((hp, max_hp, combo_depth, dir))
        }
        fn begin_parry(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error> {
            Ok((hp, max_hp, combo_depth))
        }
        fn begin_perfect_parry(hp: f32, max_hp: f32, combo_depth: u32, dir: AttackDir) -> Result<(f32, f32, u32, AttackDir), anyhow::Error> {
            Ok((hp, max_hp, combo_depth, dir))
        }
        fn begin_dodge(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error> {
            Ok((hp, max_hp, combo_depth))
        }
        fn resolve_hit(hp: f32, max_hp: f32, combo_depth: u32, damage: f32, target_hp: &mut f32) -> Result<(f32, f32, u32), anyhow::Error> {
            *target_hp = (*target_hp - damage).max(0.0);
            Ok((hp, max_hp, (combo_depth + 1).min(5)))
        }
        fn resolve_blocked(hp: f32, max_hp: f32, _combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error> {
            Ok((hp, max_hp, 0))
        }
        fn resolve_parry(hp: f32, max_hp: f32, combo_depth: u32, outcome: ParryOutcome, incoming_damage: f32) -> Result<(f32, f32, u32, ParryOutcome), anyhow::Error> {
            let new_hp = match outcome {
                ParryOutcome::Perfect => hp,
                ParryOutcome::Normal  => (hp - incoming_damage * 0.1).max(0.0),
                ParryOutcome::Miss    => (hp - incoming_damage).max(0.0),
            };
            Ok((new_hp, max_hp, combo_depth, outcome))
        }
        fn resolve_perfect_parry(hp: f32, max_hp: f32, combo_depth: u32, announced: AttackDir, player_dir: AttackDir, incoming_damage: f32) -> Result<(f32, f32, u32, ParryOutcome), anyhow::Error> {
            if announced == player_dir {
                Ok((hp, max_hp, combo_depth, ParryOutcome::Perfect))
            } else {
                Ok(((hp - incoming_damage * 0.1).max(0.0), max_hp, combo_depth, ParryOutcome::Normal))
            }
        }
        fn resolve_dodge(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error> {
            Ok((hp, max_hp, combo_depth))
        }
    }

    type M = Machine<DefaultLaw, Idle>;

    // ── construction ─────────────────────────────────────────────────────────

    #[test]
    fn new_machine_has_full_hp() {
        let m: M = Machine::new(100.0);
        assert_eq!(m.hp, 100.0);
        assert_eq!(m.max_hp, 100.0);
        assert_eq!(m.combo_depth, 0);
    }

    // ── Idle → Attacking → resolve_hit ───────────────────────────────────────

    #[test]
    fn attack_hit_deals_damage_and_increments_combo() {
        let m: M = Machine::new(100.0);
        let mut target = 200.0_f32;
        let (attacking, _dir) = m.begin_attack(AttackDir::Overhead);
        let idle = attacking.resolve_hit(30.0, &mut target);
        assert_eq!(target, 170.0);
        assert_eq!(idle.combo_depth, 1);
    }

    #[test]
    fn attack_resolve_blocked_resets_combo() {
        let m: M = Machine::new(100.0);
        let (attacking, _) = m.begin_attack(AttackDir::Left);
        let idle = attacking.resolve_blocked();
        assert_eq!(idle.combo_depth, 0);
    }

    // ── Idle → Parrying ───────────────────────────────────────────────────────

    #[test]
    fn perfect_parry_takes_no_damage() {
        let m: M = Machine::new(100.0);
        let parrying = m.begin_parry();
        let (idle, outcome) = parrying.resolve(ParryOutcome::Perfect, 50.0);
        assert_eq!(outcome, ParryOutcome::Perfect);
        assert_eq!(idle.hp, 100.0);
    }

    #[test]
    fn normal_parry_takes_chip_damage() {
        let m: M = Machine::new(100.0);
        let parrying = m.begin_parry();
        let (idle, _) = parrying.resolve(ParryOutcome::Normal, 50.0);
        assert!((idle.hp - 95.0).abs() < 0.01);
    }

    // ── Idle → PerfectParrying ────────────────────────────────────────────────

    #[test]
    fn matching_direction_yields_perfect_outcome() {
        let m: M = Machine::new(100.0);
        let (pp, announced) = m.begin_perfect_parry(AttackDir::Right);
        let (idle, outcome) = pp.resolve(announced, AttackDir::Right, 50.0);
        assert_eq!(outcome, ParryOutcome::Perfect);
        assert_eq!(idle.hp, 100.0);
    }

    #[test]
    fn wrong_direction_degrades_to_normal() {
        let m: M = Machine::new(100.0);
        let (pp, _) = m.begin_perfect_parry(AttackDir::Left);
        let (idle, outcome) = pp.resolve(AttackDir::Left, AttackDir::Right, 50.0);
        assert_eq!(outcome, ParryOutcome::Normal);
        assert!((idle.hp - 95.0).abs() < 0.01);
    }

    // ── Idle → Dodging ────────────────────────────────────────────────────────

    #[test]
    fn dodge_returns_to_idle_with_full_hp() {
        let m: M = Machine::new(100.0);
        let dodging = m.begin_dodge();
        let idle = dodging.resolve();
        assert_eq!(idle.hp, 100.0);
    }
}
