// Generated by ggen. DO NOT EDIT.
#![allow(unused_imports, dead_code)]

use std::marker::PhantomData;




// Zero-sized state markers


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Attacking;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Dodging;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Idle;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Parrying;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PerfectParrying;






















/// Typestate combat state machine kernel
#[derive(Debug, Clone)]
pub struct Machine<L, P> {
    pub _law: std::marker::PhantomData<L>,
    pub hp: f32,
    pub max_hp: f32,
    pub combo_depth: u32,
    pub phase: P,
}

pub trait CombatMachineLaw {
    fn begin_attack(hp: f32, max_hp: f32, combo_depth: u32, dir: crate::parry::AttackDir) -> Result<(f32, f32, u32, crate::parry::AttackDir), anyhow::Error>;
    fn begin_parry(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error>;
    fn begin_perfect_parry(hp: f32, max_hp: f32, combo_depth: u32, dir: crate::parry::AttackDir) -> Result<(f32, f32, u32, crate::parry::AttackDir), anyhow::Error>;
    fn begin_dodge(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error>;
    fn resolve_hit(hp: f32, max_hp: f32, combo_depth: u32, damage: f32, target_hp: &mut f32) -> Result<(f32, f32, u32), anyhow::Error>;
    fn resolve_blocked(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error>;
    fn resolve_parry(hp: f32, max_hp: f32, combo_depth: u32, outcome: crate::parry::ParryOutcome, incoming_damage: f32) -> Result<(f32, f32, u32, crate::parry::ParryOutcome), anyhow::Error>;
    fn resolve_perfect_parry(hp: f32, max_hp: f32, combo_depth: u32, announced: crate::parry::AttackDir, player_dir: crate::parry::AttackDir, incoming_damage: f32) -> Result<(f32, f32, u32, crate::parry::ParryOutcome), anyhow::Error>;
    fn resolve_dodge(hp: f32, max_hp: f32, combo_depth: u32) -> Result<(f32, f32, u32), anyhow::Error>;
}

impl<L: CombatMachineLaw> Machine<L, Idle> {
    pub fn new(hp: f32) -> Self {
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp: hp,
            combo_depth: 0,
            phase: Idle,
        }
    }

    pub fn begin_attack(self, dir: crate::parry::AttackDir) -> (Machine<L, Attacking>, crate::parry::AttackDir) {
        let (hp, max_hp, combo_depth, out_dir) = L::begin_attack(self.hp, self.max_hp, self.combo_depth, dir).unwrap();
        (
            Machine {
                _law: std::marker::PhantomData,
                hp,
                max_hp,
                combo_depth,
                phase: Attacking,
            },
            out_dir,
        )
    }

    pub fn begin_parry(self) -> Machine<L, Parrying> {
        let (hp, max_hp, combo_depth) = L::begin_parry(self.hp, self.max_hp, self.combo_depth).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Parrying,
        }
    }

    pub fn begin_perfect_parry(self, dir: crate::parry::AttackDir) -> (Machine<L, PerfectParrying>, crate::parry::AttackDir) {
        let (hp, max_hp, combo_depth, out_dir) = L::begin_perfect_parry(self.hp, self.max_hp, self.combo_depth, dir).unwrap();
        (
            Machine {
                _law: std::marker::PhantomData,
                hp,
                max_hp,
                combo_depth,
                phase: PerfectParrying,
            },
            out_dir,
        )
    }

    pub fn begin_dodge(self) -> Machine<L, Dodging> {
        let (hp, max_hp, combo_depth) = L::begin_dodge(self.hp, self.max_hp, self.combo_depth).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Dodging,
        }
    }
}

impl<L: CombatMachineLaw> Machine<L, Attacking> {
    pub fn resolve_hit(self, damage: f32, target_hp: &mut f32) -> Machine<L, Idle> {
        let (hp, max_hp, combo_depth) = L::resolve_hit(self.hp, self.max_hp, self.combo_depth, damage, target_hp).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Idle,
        }
    }

    pub fn resolve_blocked(self) -> Machine<L, Idle> {
        let (hp, max_hp, combo_depth) = L::resolve_blocked(self.hp, self.max_hp, self.combo_depth).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Idle,
        }
    }
}

impl<L: CombatMachineLaw> Machine<L, Parrying> {
    pub fn resolve(self, outcome: crate::parry::ParryOutcome, incoming_damage: f32) -> (Machine<L, Idle>, crate::parry::ParryOutcome) {
        let (hp, max_hp, combo_depth, out_outcome) = L::resolve_parry(self.hp, self.max_hp, self.combo_depth, outcome, incoming_damage).unwrap();
        (
            Machine {
                _law: std::marker::PhantomData,
                hp,
                max_hp,
                combo_depth,
                phase: Idle,
            },
            out_outcome,
        )
    }
}

impl<L: CombatMachineLaw> Machine<L, PerfectParrying> {
    pub fn resolve(
        self,
        announced: crate::parry::AttackDir,
        player_dir: crate::parry::AttackDir,
        incoming_damage: f32,
    ) -> (Machine<L, Idle>, crate::parry::ParryOutcome) {
        let (hp, max_hp, combo_depth, outcome) = L::resolve_perfect_parry(self.hp, self.max_hp, self.combo_depth, announced, player_dir, incoming_damage).unwrap();
        (
            Machine {
                _law: std::marker::PhantomData,
                hp,
                max_hp,
                combo_depth,
                phase: Idle,
            },
            outcome,
        )
    }
}

impl<L: CombatMachineLaw> Machine<L, Dodging> {
    pub fn resolve(self) -> Machine<L, Idle> {
        let (hp, max_hp, combo_depth) = L::resolve_dodge(self.hp, self.max_hp, self.combo_depth).unwrap();
        Machine {
            _law: std::marker::PhantomData,
            hp,
            max_hp,
            combo_depth,
            phase: Idle,
        }
    }
}

