// Generated by ggen. DO NOT EDIT.
#![allow(unused_imports, dead_code)]

use std::marker::PhantomData;




// Zero-sized state markers


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Authenticated;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Connecting;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Disconnected;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InLobby;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InMatch;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Spectating;


























/// Typestate session state machine kernel
#[derive(Debug, Clone)]
pub struct Machine<L, P> {
    pub _law: std::marker::PhantomData<L>,
    pub player_id: u64,
    pub username: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub phase: P,
}

pub trait SessionMachineLaw {
    fn authenticate(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>, token_valid: bool) -> Result<(), crate::session::SessionError>;
    fn reject(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
    fn enter_lobby(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
    fn disconnect(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
    fn enter_match(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>, match_id: u64) -> Result<(), crate::session::SessionError>;
    fn spectate(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>, match_id: u64) -> Result<(), crate::session::SessionError>;
    fn match_complete(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
    fn leave_spectate(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
}

impl<L: SessionMachineLaw> Machine<L, Connecting> {
    pub fn new(player_id: u64, username: String) -> Self {
        Machine {
            _law: std::marker::PhantomData,
            player_id,
            username,
            created_at: chrono::Utc::now(),
            phase: Connecting,
        }
    }

    pub fn authenticate(
        self,
        token_valid: bool,
    ) -> Result<Machine<L, Authenticated>, crate::session::SessionError> {
        L::authenticate(self.player_id, &self.username, self.created_at, token_valid)?;
        Ok(Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Authenticated,
        })
    }

    pub fn reject(self) -> Machine<L, Disconnected> {
        let _ = L::reject(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}

impl<L: SessionMachineLaw> Machine<L, Authenticated> {
    pub fn enter_lobby(self) -> Machine<L, InLobby> {
        let _ = L::enter_lobby(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: InLobby,
        }
    }

    pub fn disconnect(self) -> Machine<L, Disconnected> {
        let _ = L::disconnect(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}

impl<L: SessionMachineLaw> Machine<L, InLobby> {
    pub fn enter_match(self, match_id: u64) -> (Machine<L, InMatch>, u64) {
        let _ = L::enter_match(self.player_id, &self.username, self.created_at, match_id);
        (
            Machine {
                _law: std::marker::PhantomData,
                player_id: self.player_id,
                username: self.username,
                created_at: self.created_at,
                phase: InMatch,
            },
            match_id,
        )
    }

    pub fn spectate(self, match_id: u64) -> (Machine<L, Spectating>, u64) {
        let _ = L::spectate(self.player_id, &self.username, self.created_at, match_id);
        (
            Machine {
                _law: std::marker::PhantomData,
                player_id: self.player_id,
                username: self.username,
                created_at: self.created_at,
                phase: Spectating,
            },
            match_id,
        )
    }

    pub fn disconnect(self) -> Machine<L, Disconnected> {
        let _ = L::disconnect(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}

impl<L: SessionMachineLaw> Machine<L, InMatch> {
    pub fn match_complete(self) -> Machine<L, InLobby> {
        let _ = L::match_complete(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: InLobby,
        }
    }

    pub fn disconnect(self) -> Machine<L, Disconnected> {
        let _ = L::disconnect(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}

impl<L: SessionMachineLaw> Machine<L, Spectating> {
    pub fn leave_spectate(self) -> Machine<L, InLobby> {
        let _ = L::leave_spectate(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: InLobby,
        }
    }

    pub fn disconnect(self) -> Machine<L, Disconnected> {
        let _ = L::disconnect(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}


#[cfg(test)]
mod tests {
    use super::*;
    use crate::session::SessionError;

    // ── DefaultLaw: passthrough implementation ─────────────────────────────────
    struct DefaultLaw;
    impl SessionMachineLaw for DefaultLaw {
        fn authenticate(_: u64, _: &str, _: chrono::DateTime<chrono::Utc>, token_valid: bool)
            -> Result<(), SessionError>
        {
            if token_valid { Ok(()) } else { Err(SessionError::AuthFailed) }
        }
        fn reject(_: u64, _: &str, _: chrono::DateTime<chrono::Utc>) -> Result<(), SessionError> { Ok(()) }
        fn enter_lobby(_: u64, _: &str, _: chrono::DateTime<chrono::Utc>) -> Result<(), SessionError> { Ok(()) }
        fn disconnect(_: u64, _: &str, _: chrono::DateTime<chrono::Utc>) -> Result<(), SessionError> { Ok(()) }
        fn enter_match(_: u64, _: &str, _: chrono::DateTime<chrono::Utc>, _: u64) -> Result<(), SessionError> { Ok(()) }
        fn spectate(_: u64, _: &str, _: chrono::DateTime<chrono::Utc>, _: u64) -> Result<(), SessionError> { Ok(()) }
        fn match_complete(_: u64, _: &str, _: chrono::DateTime<chrono::Utc>) -> Result<(), SessionError> { Ok(()) }
        fn leave_spectate(_: u64, _: &str, _: chrono::DateTime<chrono::Utc>) -> Result<(), SessionError> { Ok(()) }
    }

    fn connecting() -> Machine<DefaultLaw, Connecting> {
        Machine::<DefaultLaw, Connecting>::new(1, "Amuro".into())
    }

    // ── Construction ─────────────────────────────────────────────────────────

    #[test]
    fn new_starts_in_connecting_with_player_data() {
        let m = connecting();
        assert_eq!(m.player_id, 1);
        assert_eq!(m.username, "Amuro");
    }

    // ── Connecting → Authenticated ────────────────────────────────────────────

    #[test]
    fn authenticate_with_valid_token_succeeds() {
        let auth = connecting().authenticate(true).unwrap();
        assert_eq!(auth.player_id, 1);
        assert_eq!(auth.phase, Authenticated);
    }

    #[test]
    fn authenticate_with_invalid_token_returns_auth_failed() {
        let result = connecting().authenticate(false);
        assert!(matches!(result, Err(SessionError::AuthFailed)));
    }

    #[test]
    fn reject_produces_disconnected() {
        let disc = connecting().reject();
        assert_eq!(disc.phase, Disconnected);
        assert_eq!(disc.player_id, 1);
    }

    // ── Authenticated → InLobby / Disconnected ────────────────────────────────

    #[test]
    fn enter_lobby_from_authenticated() {
        let lobby = connecting().authenticate(true).unwrap().enter_lobby();
        assert_eq!(lobby.phase, InLobby);
    }

    #[test]
    fn disconnect_from_authenticated_gives_disconnected() {
        let disc = connecting().authenticate(true).unwrap().disconnect();
        assert_eq!(disc.phase, Disconnected);
    }

    // ── InLobby → InMatch / Spectating / Disconnected ────────────────────────

    #[test]
    fn enter_match_returns_in_match_and_match_id() {
        let lobby = connecting().authenticate(true).unwrap().enter_lobby();
        let (m, mid) = lobby.enter_match(42);
        assert_eq!(m.phase, InMatch);
        assert_eq!(mid, 42);
    }

    #[test]
    fn spectate_returns_spectating_and_match_id() {
        let lobby = connecting().authenticate(true).unwrap().enter_lobby();
        let (s, mid) = lobby.spectate(99);
        assert_eq!(s.phase, Spectating);
        assert_eq!(mid, 99);
    }

    #[test]
    fn disconnect_from_lobby_gives_disconnected() {
        let lobby = connecting().authenticate(true).unwrap().enter_lobby();
        let disc = lobby.disconnect();
        assert_eq!(disc.phase, Disconnected);
    }

    // ── InMatch → InLobby / Disconnected ─────────────────────────────────────

    #[test]
    fn match_complete_returns_to_lobby() {
        let (in_match, _) = connecting().authenticate(true).unwrap()
            .enter_lobby().enter_match(1);
        let lobby = in_match.match_complete();
        assert_eq!(lobby.phase, InLobby);
    }

    #[test]
    fn disconnect_from_in_match_gives_disconnected() {
        let (in_match, _) = connecting().authenticate(true).unwrap()
            .enter_lobby().enter_match(1);
        let disc = in_match.disconnect();
        assert_eq!(disc.phase, Disconnected);
    }

    // ── Spectating → InLobby / Disconnected ──────────────────────────────────

    #[test]
    fn leave_spectate_returns_to_lobby() {
        let (spec, _) = connecting().authenticate(true).unwrap()
            .enter_lobby().spectate(7);
        let lobby = spec.leave_spectate();
        assert_eq!(lobby.phase, InLobby);
    }

    #[test]
    fn disconnect_from_spectating() {
        let (spec, _) = connecting().authenticate(true).unwrap()
            .enter_lobby().spectate(7);
        let disc = spec.disconnect();
        assert_eq!(disc.phase, Disconnected);
    }

    // ── State marker distinctness ─────────────────────────────────────────────

    #[test]
    fn state_markers_are_copy_and_eq() {
        let a = Authenticated;
        let b = a; // Copy
        assert_eq!(a, b);
        assert_ne!(InLobby, Disconnected); // different types — compile-time only
    }

    // ── Username preserved through full lifecycle ──────────────────────────────

    #[test]
    fn username_preserved_through_full_chain() {
        let (in_match, _) = Machine::<DefaultLaw, Connecting>::new(99, "Char".into())
            .authenticate(true).unwrap()
            .enter_lobby()
            .enter_match(42);
        assert_eq!(in_match.username, "Char");
        let lobby = in_match.match_complete();
        assert_eq!(lobby.username, "Char");
    }
}
