// Generated by ggen. DO NOT EDIT.
#![allow(unused_imports, dead_code)]

use std::marker::PhantomData;




// Zero-sized state markers


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Authenticated;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Connecting;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Disconnected;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InLobby;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InMatch;



#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Spectating;


























/// Typestate session state machine kernel
#[derive(Debug, Clone)]
pub struct Machine<L, P> {
    pub _law: std::marker::PhantomData<L>,
    pub player_id: u64,
    pub username: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub phase: P,
}

pub trait SessionMachineLaw {
    fn authenticate(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>, token_valid: bool) -> Result<(), crate::session::SessionError>;
    fn reject(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
    fn enter_lobby(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
    fn disconnect(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
    fn enter_match(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>, match_id: u64) -> Result<(), crate::session::SessionError>;
    fn spectate(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>, match_id: u64) -> Result<(), crate::session::SessionError>;
    fn match_complete(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
    fn leave_spectate(player_id: u64, username: &str, created_at: chrono::DateTime<chrono::Utc>) -> Result<(), crate::session::SessionError>;
}

impl<L: SessionMachineLaw> Machine<L, Connecting> {
    pub fn new(player_id: u64, username: String) -> Self {
        Machine {
            _law: std::marker::PhantomData,
            player_id,
            username,
            created_at: chrono::Utc::now(),
            phase: Connecting,
        }
    }

    pub fn authenticate(
        self,
        token_valid: bool,
    ) -> Result<Machine<L, Authenticated>, crate::session::SessionError> {
        L::authenticate(self.player_id, &self.username, self.created_at, token_valid)?;
        Ok(Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Authenticated,
        })
    }

    pub fn reject(self) -> Machine<L, Disconnected> {
        let _ = L::reject(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}

impl<L: SessionMachineLaw> Machine<L, Authenticated> {
    pub fn enter_lobby(self) -> Machine<L, InLobby> {
        let _ = L::enter_lobby(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: InLobby,
        }
    }

    pub fn disconnect(self) -> Machine<L, Disconnected> {
        let _ = L::disconnect(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}

impl<L: SessionMachineLaw> Machine<L, InLobby> {
    pub fn enter_match(self, match_id: u64) -> (Machine<L, InMatch>, u64) {
        let _ = L::enter_match(self.player_id, &self.username, self.created_at, match_id);
        (
            Machine {
                _law: std::marker::PhantomData,
                player_id: self.player_id,
                username: self.username,
                created_at: self.created_at,
                phase: InMatch,
            },
            match_id,
        )
    }

    pub fn spectate(self, match_id: u64) -> (Machine<L, Spectating>, u64) {
        let _ = L::spectate(self.player_id, &self.username, self.created_at, match_id);
        (
            Machine {
                _law: std::marker::PhantomData,
                player_id: self.player_id,
                username: self.username,
                created_at: self.created_at,
                phase: Spectating,
            },
            match_id,
        )
    }

    pub fn disconnect(self) -> Machine<L, Disconnected> {
        let _ = L::disconnect(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}

impl<L: SessionMachineLaw> Machine<L, InMatch> {
    pub fn match_complete(self) -> Machine<L, InLobby> {
        let _ = L::match_complete(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: InLobby,
        }
    }

    pub fn disconnect(self) -> Machine<L, Disconnected> {
        let _ = L::disconnect(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}

impl<L: SessionMachineLaw> Machine<L, Spectating> {
    pub fn leave_spectate(self) -> Machine<L, InLobby> {
        let _ = L::leave_spectate(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: InLobby,
        }
    }

    pub fn disconnect(self) -> Machine<L, Disconnected> {
        let _ = L::disconnect(self.player_id, &self.username, self.created_at);
        Machine {
            _law: std::marker::PhantomData,
            player_id: self.player_id,
            username: self.username,
            created_at: self.created_at,
            phase: Disconnected,
        }
    }
}

