use crate::ast::*;
use crate::types::*;

/// Serializes a Blueprint AST to UE4 T3D clipboard format.
/// The output can be pasted directly into the UE4 Blueprint editor (Ctrl+V).
pub struct T3dSerializer;

/// All-zeros GUID used for PersistentGuid in T3D pin output.
const ZERO_GUID: &str = "00000000000000000000000000000000";

/// Maps ContainerType to the UE4 T3D string representation.
fn container_ue_str(c: &ContainerType) -> &'static str {
    match c {
        ContainerType::None => "None",
        ContainerType::Array => "Array",
        ContainerType::Set => "Set",
        ContainerType::Map => "Map",
    }
}

impl T3dSerializer {
    /// Serialize all graphs in a Blueprint to T3D format.
    /// Returns the full T3D text ready for pasting into UE4.
    pub fn serialize(blueprint: &Blueprint) -> String {
        let mut output = String::new();
        for graph in &blueprint.graphs {
            // Add a comment indicating which graph when there are multiple
            if blueprint.graphs.len() > 1 {
                output.push_str(&format!("// Graph: {}\n", graph.name));
            }
            for node in &graph.nodes {
                output.push_str(&Self::serialize_node(node));
            }
        }
        output
    }

    /// Serialize a single graph to T3D format.
    pub fn serialize_graph(graph: &BpGraph) -> String {
        let mut output = String::new();
        for node in &graph.nodes {
            output.push_str(&Self::serialize_node(node));
        }
        output
    }

    /// Serialize with a header comment explaining the source.
    pub fn serialize_with_header(blueprint: &Blueprint) -> String {
        let mut out = format!(
            "// Generated by blueprint-rs — Blueprint: {}, Parent: {}\n",
            blueprint.name, blueprint.parent_class
        );
        out.push_str(&Self::serialize(blueprint));
        out
    }

    /// Serialize a single node to T3D format.
    pub fn serialize_node(node: &BpNode) -> String {
        let mut out = String::new();

        // Begin Object line
        out.push_str(&format!(
            "Begin Object Class={} Name=\"{}\"\n",
            node.class, node.name
        ));

        // Node properties come before NodePosX/NodePosY/NodeGuid.
        // NodeProperties is a HashMap so iteration order is non-deterministic;
        // sort by key for stable, reproducible output.
        let mut props: Vec<(&String, &String)> = node.properties.iter().collect();
        props.sort_by_key(|(k, _)| k.as_str());
        for (key, val) in props {
            out.push_str(&format!("   {}={}\n", key, val));
        }

        // Node position
        out.push_str(&format!("   NodePosX={}\n", node.pos.x));
        out.push_str(&format!("   NodePosY={}\n", node.pos.y));

        // Node GUID
        out.push_str(&format!("   NodeGuid={}\n", node.id));

        // Pins
        for pin in &node.pins {
            out.push_str(&Self::serialize_pin(pin));
        }

        // End Object
        out.push_str("End Object\n");

        out
    }

    fn serialize_pin(pin: &Pin) -> String {
        let mut parts: Vec<String> = Vec::new();

        // PinId
        parts.push(format!("PinId={}", pin.id));

        // PinName — always quoted
        parts.push(format!("PinName=\"{}\"", pin.name));

        // Direction — only emitted for Output pins; Input pins omit this field
        if pin.direction == PinDirection::Output {
            parts.push("Direction=\"EGPD_Output\"".to_string());
        }

        // PinType.PinCategory
        parts.push(format!(
            "PinType.PinCategory=\"{}\"",
            pin.pin_type.category.as_str()
        ));

        // PinType.PinSubCategoryObject: None or the path string
        match &pin.pin_type.sub_category_object {
            Some(obj) => parts.push(format!("PinType.PinSubCategoryObject={}", obj)),
            None => parts.push("PinType.PinSubCategoryObject=None".to_string()),
        }

        // PinValueType — always empty parens for non-map types
        parts.push("PinType.PinValueType=()".to_string());

        // ContainerType
        parts.push(format!(
            "PinType.ContainerType={}",
            container_ue_str(&pin.pin_type.container)
        ));

        // Reference / const flags
        parts.push(format!(
            "PinType.bIsReference={}",
            if pin.pin_type.is_reference { "True" } else { "False" }
        ));
        parts.push(format!(
            "PinType.bIsConst={}",
            if pin.pin_type.is_const { "True" } else { "False" }
        ));
        // is_weak_pointer is not in the AST type; always False in output
        parts.push("PinType.bIsWeakPointer=False".to_string());

        // DefaultValue — only emitted when set
        if let Some(dv) = &pin.default_value {
            parts.push(format!("DefaultValue=\"{}\"", dv));
        }

        // PersistentGuid — always zero in T3D clipboard output
        parts.push(format!("PersistentGuid={}", ZERO_GUID));

        // Visibility / behaviour flags
        parts.push(format!(
            "bHidden={}",
            if pin.is_hidden { "True" } else { "False" }
        ));
        parts.push(format!(
            "bNotConnectable={}",
            if pin.is_not_connectable { "True" } else { "False" }
        ));
        parts.push("bDefaultValueIsReadOnly=False".to_string());
        parts.push("bDefaultValueIsIgnored=False".to_string());
        parts.push(format!(
            "bAdvancedView={}",
            if pin.is_advanced_view { "True" } else { "False" }
        ));
        parts.push(format!(
            "bOrphanedPin={}",
            if pin.is_orphaned { "True" } else { "False" }
        ));

        // LinkedTo — connections to other pins.
        // Format: LinkedTo=(<node_name> <pin_guid>,)
        // The trailing comma inside the parens is required by the UE4 parser.
        if !pin.linked_to.is_empty() {
            let links: String = pin
                .linked_to
                .iter()
                .map(|r| format!("{} {},", r.node_name, r.pin_id))
                .collect::<Vec<_>>()
                .join("");
            parts.push(format!("LinkedTo=({})", links));
        }

        // The trailing comma inside the outer parens is also required by UE4.
        format!("   CustomProperties Pin ({},)\n", parts.join(","))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_event_node() -> BpNode {
        BpNode::new(
            "/Script/BlueprintGraph.K2Node_Event",
            "K2Node_Event_0",
        )
        .at(64, -16)
        .with_property(
            "EventReference",
            "(MemberParent=Class'/Script/Engine.Actor',MemberName=\"ReceiveBeginPlay\")",
        )
        .with_property("bOverrideFunction", "True")
        .with_pin({
            let mut p = Pin::new(
                "OutputDelegate",
                PinDirection::Output,
                PinType {
                    category: PinCategory::Delegate,
                    sub_category: None,
                    sub_category_object: None,
                    container: ContainerType::None,
                    is_reference: false,
                    is_const: false,
                },
            );
            p.is_hidden = true;
            p.is_not_connectable = true;
            p
        })
        .with_pin(Pin::exec_output("then"))
    }

    #[test]
    fn test_event_node_structure() {
        let node = make_event_node();
        let t3d = T3dSerializer::serialize_node(&node);

        assert!(t3d.contains("Begin Object"), "missing Begin Object:\n{}", t3d);
        assert!(t3d.contains("K2Node_Event_0"), "missing node name:\n{}", t3d);
        assert!(t3d.contains("NodeGuid="), "missing NodeGuid:\n{}", t3d);
        assert!(t3d.contains("End Object"), "missing End Object:\n{}", t3d);
        assert!(
            t3d.contains("/Script/BlueprintGraph.K2Node_Event"),
            "missing class:\n{}",
            t3d
        );
        assert!(t3d.contains("NodePosX=64"), "missing NodePosX:\n{}", t3d);
        assert!(t3d.contains("NodePosY=-16"), "missing NodePosY:\n{}", t3d);
        assert!(
            t3d.contains("CustomProperties Pin"),
            "missing pin:\n{}",
            t3d
        );
        // Output pins include Direction field
        assert!(
            t3d.contains("Direction=\"EGPD_Output\""),
            "missing Direction on output pin:\n{}",
            t3d
        );
    }

    #[test]
    fn test_connected_exec_pin_produces_linked_to() {
        // Build a graph with two nodes connected by exec pins
        let mut graph = BpGraph::new("TestGraph");

        let event_node = BpNode::new(
            "/Script/BlueprintGraph.K2Node_Event",
            "K2Node_Event_0",
        )
        .at(64, -16)
        .with_pin(Pin::exec_output("then"));

        let call_node = BpNode::new(
            "/Script/BlueprintGraph.K2Node_CallFunction",
            "K2Node_CallFunction_0",
        )
        .at(320, -16)
        .with_pin(Pin::exec_input("execute"))
        .with_pin(Pin::exec_output("then"));

        graph.add_node(event_node);
        graph.add_node(call_node);

        // Wire K2Node_Event_0:then -> K2Node_CallFunction_0:execute
        graph.connect("K2Node_Event_0", "then", "K2Node_CallFunction_0", "execute");

        let t3d = T3dSerializer::serialize_graph(&graph);

        assert!(
            t3d.contains("LinkedTo="),
            "expected LinkedTo in output, got:\n{}",
            t3d
        );
        assert!(
            t3d.contains("K2Node_CallFunction_0"),
            "expected target node name in LinkedTo, got:\n{}",
            t3d
        );
        assert!(
            t3d.contains("K2Node_Event_0"),
            "expected source node name in LinkedTo, got:\n{}",
            t3d
        );
    }

    #[test]
    fn test_input_pin_has_no_direction_attribute() {
        let node = BpNode::new(
            "/Script/BlueprintGraph.K2Node_CallFunction",
            "K2Node_CallFunction_0",
        )
        .with_pin(Pin::exec_input("execute"));

        let t3d = T3dSerializer::serialize_node(&node);

        // The "execute" pin is an input pin and must NOT have Direction= in its CustomProperties
        let exec_pin_line = t3d
            .lines()
            .find(|l| l.contains("PinName=\"execute\""))
            .unwrap_or("");
        assert!(
            !exec_pin_line.contains("Direction="),
            "input pin must not have Direction attribute, got: {}",
            exec_pin_line
        );
    }

    #[test]
    fn test_default_value_serialized() {
        let mut pin = Pin::data_input("InString", PinType::string());
        pin.default_value = Some("Hello!".to_string());

        let node = BpNode::new(
            "/Script/BlueprintGraph.K2Node_CallFunction",
            "K2Node_CallFunction_0",
        )
        .with_pin(pin);

        let t3d = T3dSerializer::serialize_node(&node);
        assert!(
            t3d.contains("DefaultValue=\"Hello!\""),
            "missing DefaultValue in output:\n{}",
            t3d
        );
    }

    #[test]
    fn test_serialize_with_header() {
        let bp = Blueprint::new("MyBlueprint", "Actor");
        let t3d = T3dSerializer::serialize_with_header(&bp);
        assert!(
            t3d.starts_with("// Generated by blueprint-rs"),
            "missing header comment:\n{}",
            t3d
        );
        assert!(
            t3d.contains("MyBlueprint"),
            "missing blueprint name in header:\n{}",
            t3d
        );
        assert!(
            t3d.contains("Actor"),
            "missing parent class in header:\n{}",
            t3d
        );
    }

    #[test]
    fn test_multiple_graphs_have_comments() {
        let mut bp = Blueprint::new("MyBlueprint", "Actor");
        // Blueprint::new adds EventGraph automatically; add a second one
        bp.function_graph("MyFunction");

        let t3d = T3dSerializer::serialize(&bp);
        assert!(
            t3d.contains("// Graph: EventGraph"),
            "missing EventGraph comment:\n{}",
            t3d
        );
        assert!(
            t3d.contains("// Graph: MyFunction"),
            "missing MyFunction comment:\n{}",
            t3d
        );
    }

    #[test]
    fn test_pin_type_flags_false() {
        // Verify bIsReference and bIsConst default to False
        let node = BpNode::new(
            "/Script/BlueprintGraph.K2Node_CallFunction",
            "K2Node_CallFunction_0",
        )
        .with_pin(Pin::data_input("Value", PinType::int()));

        let t3d = T3dSerializer::serialize_node(&node);
        assert!(
            t3d.contains("PinType.bIsReference=False"),
            "expected bIsReference=False:\n{}",
            t3d
        );
        assert!(
            t3d.contains("PinType.bIsConst=False"),
            "expected bIsConst=False:\n{}",
            t3d
        );
        assert!(
            t3d.contains("PinType.bIsWeakPointer=False"),
            "expected bIsWeakPointer=False:\n{}",
            t3d
        );
    }
}
